"""
TythanAI — Self-Calibration Engine
Automatically adjusts per-rule confidence thresholds based on FP history in SQLite.
"""
from __future__ import annotations

import json
import logging
import os
import sqlite3
from datetime import datetime, timezone
from pathlib import Path
from typing import Dict, List, Optional

from pydantic import BaseModel, Field

logger = logging.getLogger("ghost.self_calibration")

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

DEFAULT_THRESHOLD: float = 0.5
FP_RATE_HIGH: float = 0.30   # if fp_rate > 30% → raise threshold by 0.10
FP_RATE_LOW: float = 0.05    # if fp_rate < 5% and total > 10 → lower threshold by 0.05
_MIN_THRESHOLD: float = 0.30
_MAX_THRESHOLD: float = 0.95

# ---------------------------------------------------------------------------
# Pydantic models
# ---------------------------------------------------------------------------


class RuleCalibration(BaseModel):
    rule_id: str
    total_findings: int
    fp_count: int
    fp_rate: float           # 0.0-1.0
    current_threshold: float
    suggested_threshold: float
    action: str              # "raise_threshold" | "lower_threshold" | "keep"


class CalibrationReport(BaseModel):
    calibrated_at: str
    total_rules_analyzed: int
    rules_adjusted: int
    rules: List[RuleCalibration]
    config_path: str

    def to_markdown(self) -> str:
        lines: List[str] = []
        lines.append("# Confidence Threshold Calibration Report")
        lines.append("")
        lines.append(f"**Calibrated at:** {self.calibrated_at}")
        lines.append(f"**Total rules analyzed:** {self.total_rules_analyzed}")
        lines.append(f"**Rules adjusted:** {self.rules_adjusted}")
        lines.append(f"**Config path:** `{self.config_path}`")
        lines.append("")
        lines.append("## Rule-Level Calibration")
        lines.append("")
        lines.append("| Rule ID | Total | FP Count | FP Rate | Current Threshold | Suggested | Action |")
        lines.append("|---------|-------|----------|---------|-------------------|-----------|--------|")
        for r in self.rules:
            fp_pct = f"{r.fp_rate * 100:.1f}%"
            lines.append(
                f"| `{r.rule_id}` | {r.total_findings} | {r.fp_count} | {fp_pct} "
                f"| {r.current_threshold:.2f} | {r.suggested_threshold:.2f} | {r.action} |"
            )
        lines.append("")
        lines.append("---")
        lines.append(f"*Generated by TythanAI Self-Calibration Engine*")
        return "\n".join(lines)


# ---------------------------------------------------------------------------
# Engine
# ---------------------------------------------------------------------------


class SelfCalibrationEngine:
    """Automatically adjusts per-rule confidence thresholds based on FP history."""

    def __init__(
        self,
        db_path: Optional[str] = None,
        config_path: Optional[str] = None,
    ) -> None:
        if db_path is not None:
            self.db_path = db_path
        else:
            self.db_path = os.environ.get("GHOST_DB_PATH", "/tmp/ghost_security.db")
        self.config_path = config_path or "config/calibration.json"

    # ------------------------------------------------------------------
    # Internal helpers
    # ------------------------------------------------------------------

    def _get_fp_history(self, db_path: str) -> Dict[str, Dict]:
        """Query findings table, return {rule_id: {total: N, fp_count: M}}.

        Handles missing is_fp and suppressed columns gracefully.
        """
        result: Dict[str, Dict] = {}

        try:
            conn = sqlite3.connect(db_path)
            conn.row_factory = sqlite3.Row
            cursor = conn.cursor()

            # Discover which columns exist
            try:
                cursor.execute("SELECT * FROM findings LIMIT 0")
                col_names = {desc[0].lower() for desc in cursor.description}
            except sqlite3.OperationalError:
                # Table doesn't exist
                conn.close()
                return result

            has_is_fp = "is_fp" in col_names
            has_suppressed = "suppressed" in col_names

            # Build FP detection expression
            fp_parts: List[str] = []
            if has_is_fp:
                fp_parts.append("is_fp = 1")
            else:
                fp_parts.append("0")
            if has_suppressed:
                fp_parts.append("suppressed = 1")

            fp_expr = " OR ".join(fp_parts) if fp_parts else "0"

            sql = f"""
                SELECT
                    rule_id,
                    COUNT(*) AS total,
                    SUM(CASE WHEN {fp_expr} THEN 1 ELSE 0 END) AS fp_count
                FROM findings
                GROUP BY rule_id
            """
            rows = cursor.execute(sql).fetchall()
            for row in rows:
                result[row["rule_id"]] = {
                    "total": int(row["total"] or 0),
                    "fp_count": int(row["fp_count"] or 0),
                }

        except sqlite3.Error as exc:
            logger.warning("DB error reading FP history from %s: %s", db_path, exc)
        except Exception as exc:  # noqa: BLE001
            logger.warning("Unexpected error reading FP history: %s", exc)
        finally:
            try:
                conn.close()
            except Exception:
                pass

        return result

    def _load_current_thresholds(self, config_path: str) -> Dict[str, float]:
        """Load existing calibration thresholds from JSON file."""
        path = Path(config_path)
        if not path.exists():
            return {}
        try:
            with path.open("r", encoding="utf-8") as fh:
                data = json.load(fh)
            # Accept both {rule_id: threshold} and {rule_id: {threshold: ...}} shapes
            thresholds: Dict[str, float] = {}
            for rule_id, value in data.items():
                if isinstance(value, (int, float)):
                    thresholds[rule_id] = float(value)
                elif isinstance(value, dict) and "threshold" in value:
                    thresholds[rule_id] = float(value["threshold"])
            return thresholds
        except (json.JSONDecodeError, OSError, ValueError) as exc:
            logger.warning("Could not load calibration config from %s: %s", config_path, exc)
            return {}

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def run(self, db_path: Optional[str] = None) -> CalibrationReport:
        """Run calibration and return a report. Saves updated thresholds to config_path."""
        effective_db = db_path or self.db_path
        fp_history = self._get_fp_history(effective_db)
        current_thresholds = self._load_current_thresholds(self.config_path)

        calibrations: List[RuleCalibration] = []
        updated_thresholds: Dict[str, float] = dict(current_thresholds)
        rules_adjusted = 0

        for rule_id, stats in fp_history.items():
            total = stats["total"]
            fp_count = stats["fp_count"]
            fp_rate = fp_count / total if total > 0 else 0.0

            current = current_thresholds.get(rule_id, DEFAULT_THRESHOLD)

            if fp_rate > FP_RATE_HIGH:
                suggested = round(min(current + 0.10, _MAX_THRESHOLD), 4)
                action = "raise_threshold"
            elif fp_rate < FP_RATE_LOW and total > 10:
                suggested = round(max(current - 0.05, _MIN_THRESHOLD), 4)
                action = "lower_threshold"
            else:
                suggested = current
                action = "keep"

            if suggested != current:
                rules_adjusted += 1

            updated_thresholds[rule_id] = suggested

            calibrations.append(
                RuleCalibration(
                    rule_id=rule_id,
                    total_findings=total,
                    fp_count=fp_count,
                    fp_rate=round(fp_rate, 6),
                    current_threshold=current,
                    suggested_threshold=suggested,
                    action=action,
                )
            )

        report = CalibrationReport(
            calibrated_at=datetime.now(timezone.utc).isoformat(),
            total_rules_analyzed=len(calibrations),
            rules_adjusted=rules_adjusted,
            rules=calibrations,
            config_path=self.config_path,
        )

        # Persist updated thresholds
        try:
            self.save_config(report, config_path=self.config_path)
        except Exception as exc:
            logger.error("Failed to save calibration config: %s", exc, exc_info=True)

        return report

    def save_config(
        self,
        report: CalibrationReport,
        config_path: Optional[str] = None,
    ) -> str:
        """Write {rule_id: threshold, ...} JSON to config_path. Returns the path."""
        path = Path(config_path or self.config_path)
        path.parent.mkdir(parents=True, exist_ok=True)

        thresholds: Dict[str, float] = {
            r.rule_id: r.suggested_threshold for r in report.rules
        }
        with path.open("w", encoding="utf-8") as fh:
            json.dump(thresholds, fh, indent=2, sort_keys=True)

        logger.info("Calibration config saved to %s (%d rules)", path, len(thresholds))
        return str(path)

    def get_threshold(self, rule_id: str) -> float:
        """Return the calibrated threshold for rule_id, or DEFAULT_THRESHOLD."""
        thresholds = self._load_current_thresholds(self.config_path)
        return thresholds.get(rule_id, DEFAULT_THRESHOLD)


# ---------------------------------------------------------------------------
# Module-level convenience function
# ---------------------------------------------------------------------------


def calibrate(db_path: Optional[str] = None) -> CalibrationReport:
    """Run self-calibration against the default (or provided) database path."""
    return SelfCalibrationEngine(db_path=db_path).run(db_path=db_path)
