"""150+ Python security rules for TythanAI SAST scanner."""
from typing import Dict, List

PYTHON_RULES: List[Dict] = [
    # =========================================================================
    # INJECTION (30 rules)  PY-SEC-001 – PY-SEC-030
    # =========================================================================

    # SQL Injection
    {
        "rule_id": "PY-SEC-001",
        "name": "SQL Injection via String Formatting",
        "description": "User-controlled data is interpolated directly into a SQL query string using % or .format(), enabling SQL injection.",
        "severity": "CRITICAL",
        "cwe_id": "CWE-89",
        "pattern": r'(?:execute|executemany|raw|query)\s*\(\s*["\'][^"\']*(?:%s|%d|\{[^}]*\})[^"\']*["\']\s*%',
        "language": "python",
        "category": "INJECTION",
        "recommendation": "Use parameterized queries or prepared statements. Pass user data as query parameters, not in the query string.",
        "confidence": 0.9,
    },
    {
        "rule_id": "PY-SEC-002",
        "name": "SQL Injection via f-string",
        "description": "An f-string is used to embed a variable directly into a SQL query, which can allow SQL injection.",
        "severity": "CRITICAL",
        "cwe_id": "CWE-89",
        "pattern": r'(?:execute|executemany|raw|query)\s*\(\s*f["\'].*\{',
        "language": "python",
        "category": "INJECTION",
        "recommendation": "Replace the f-string with a parameterized query, passing user-supplied values as bound parameters.",
        "confidence": 0.95,
    },
    {
        "rule_id": "PY-SEC-003",
        "name": "SQL Injection via String Concatenation",
        "description": "A SQL query string is built by concatenating variables, which may include user-controlled data.",
        "severity": "CRITICAL",
        "cwe_id": "CWE-89",
        "pattern": r'(?:execute|cursor\.execute)\s*\(\s*(?:"[^"]*"|\'[^\']*\')\s*\+',
        "language": "python",
        "category": "INJECTION",
        "recommendation": "Use parameterized queries or ORM methods that handle escaping automatically.",
        "confidence": 0.85,
    },
    {
        "rule_id": "PY-SEC-004",
        "name": "Django ORM Raw SQL Injection",
        "description": "Django's raw() or RawSQL() is used with a string that may include user input, bypassing ORM protections.",
        "severity": "CRITICAL",
        "cwe_id": "CWE-89",
        "pattern": r'\.raw\s*\(\s*f["\']|\.raw\s*\(\s*["\'][^"\']*\+|RawSQL\s*\(\s*f["\']',
        "language": "python",
        "category": "INJECTION",
        "recommendation": "Pass user data as a separate params argument to raw() rather than embedding it in the query string.",
        "confidence": 0.9,
    },
    {
        "rule_id": "PY-SEC-005",
        "name": "SQLAlchemy Text() with User Data",
        "description": "SQLAlchemy text() is called with an f-string or concatenation, allowing SQL injection.",
        "severity": "CRITICAL",
        "cwe_id": "CWE-89",
        "pattern": r'text\s*\(\s*f["\']|text\s*\(\s*["\'][^"\']*\+',
        "language": "python",
        "category": "INJECTION",
        "recommendation": "Use SQLAlchemy's bindparams() to supply parameters safely.",
        "confidence": 0.9,
    },

    # OS Command Injection
    {
        "rule_id": "PY-SEC-006",
        "name": "OS Command Injection via os.system",
        "description": "os.system() is called with a value that may include user-controlled data, enabling command injection.",
        "severity": "CRITICAL",
        "cwe_id": "CWE-78",
        "pattern": r'os\.system\s*\(',
        "language": "python",
        "category": "INJECTION",
        "recommendation": "Replace os.system() with subprocess.run() using a list of arguments and shell=False.",
        "confidence": 0.8,
    },
    {
        "rule_id": "PY-SEC-007",
        "name": "OS Command Injection via os.popen",
        "description": "os.popen() executes a shell command and is susceptible to injection if any part of the command is user-supplied.",
        "severity": "CRITICAL",
        "cwe_id": "CWE-78",
        "pattern": r'os\.popen\s*\(',
        "language": "python",
        "category": "INJECTION",
        "recommendation": "Use subprocess.run() with a list of arguments and shell=False instead.",
        "confidence": 0.8,
    },
    {
        "rule_id": "PY-SEC-008",
        "name": "Command Injection via subprocess with shell=True",
        "description": "subprocess is invoked with shell=True, which passes the command to the OS shell and enables injection.",
        "severity": "CRITICAL",
        "cwe_id": "CWE-78",
        "pattern": r'subprocess\.(?:call|run|Popen|check_output|check_call)\s*\([^)]*shell\s*=\s*True',
        "language": "python",
        "category": "INJECTION",
        "recommendation": "Set shell=False and pass the command as a list of strings instead of a single string.",
        "confidence": 0.95,
    },
    {
        "rule_id": "PY-SEC-009",
        "name": "Command Injection via commands Module",
        "description": "The deprecated commands module (Python 2) passes arguments through the shell, enabling injection.",
        "severity": "HIGH",
        "cwe_id": "CWE-78",
        "pattern": r'commands\.(?:getoutput|getstatusoutput)\s*\(',
        "language": "python",
        "category": "INJECTION",
        "recommendation": "Migrate to subprocess with shell=False.",
        "confidence": 0.9,
    },
    {
        "rule_id": "PY-SEC-010",
        "name": "Command Injection via Paramiko exec_command",
        "description": "Paramiko exec_command may pass user-controlled data to a remote shell.",
        "severity": "HIGH",
        "cwe_id": "CWE-78",
        "pattern": r'\.exec_command\s*\(\s*(?:f["\']|[^)]*\+)',
        "language": "python",
        "category": "INJECTION",
        "recommendation": "Validate and sanitize all input before passing it to exec_command.",
        "confidence": 0.8,
    },

    # LDAP Injection
    {
        "rule_id": "PY-SEC-011",
        "name": "LDAP Injection via Unescaped Filter",
        "description": "An LDAP search filter is constructed using string formatting with potentially user-controlled data.",
        "severity": "HIGH",
        "cwe_id": "CWE-90",
        "pattern": r'ldap(?:3)?\.(?:search|search_s|search_ext)\s*\([^)]*(?:f["\']|%\s)',
        "language": "python",
        "category": "INJECTION",
        "recommendation": "Use ldap3 escape_filter_chars() to sanitize values before including them in LDAP filters.",
        "confidence": 0.8,
    },
    {
        "rule_id": "PY-SEC-012",
        "name": "LDAP DN Injection",
        "description": "An LDAP distinguished name (DN) is constructed with user-supplied data without escaping.",
        "severity": "HIGH",
        "cwe_id": "CWE-90",
        "pattern": r'(?:dn|base_dn)\s*=\s*f["\']|(?:dn|base_dn)\s*=\s*["\'][^"\']*\+',
        "language": "python",
        "category": "INJECTION",
        "recommendation": "Escape DN components using ldap3.utils.dn.escape_rdn() before constructing the DN.",
        "confidence": 0.75,
    },

    # XPath Injection
    {
        "rule_id": "PY-SEC-013",
        "name": "XPath Injection",
        "description": "An XPath expression is constructed by concatenating user data, enabling injection to alter the query logic.",
        "severity": "HIGH",
        "cwe_id": "CWE-643",
        "pattern": r'xpath\s*\(\s*(?:f["\']|["\'][^"\']*\+)',
        "language": "python",
        "category": "INJECTION",
        "recommendation": "Use XPath variable bindings instead of string concatenation for user-supplied values.",
        "confidence": 0.8,
    },

    # Template Injection
    {
        "rule_id": "PY-SEC-014",
        "name": "Server-Side Template Injection (Jinja2)",
        "description": "Jinja2 Environment.from_string() or Template() is called with user-supplied content, enabling SSTI.",
        "severity": "CRITICAL",
        "cwe_id": "CWE-94",
        "pattern": r'(?:Environment\(\)|jinja2)\s*.*?(?:from_string|Template)\s*\(',
        "language": "python",
        "category": "INJECTION",
        "recommendation": "Never render templates built from user input. Use jinja2.sandbox.SandboxedEnvironment with a static template string.",
        "confidence": 0.85,
    },
    {
        "rule_id": "PY-SEC-015",
        "name": "Server-Side Template Injection (Mako)",
        "description": "Mako Template() is called with user-supplied content, enabling SSTI.",
        "severity": "CRITICAL",
        "cwe_id": "CWE-94",
        "pattern": r'mako\.template\.Template\s*\(',
        "language": "python",
        "category": "INJECTION",
        "recommendation": "Use static template files loaded via TemplateLookup rather than creating templates from user input.",
        "confidence": 0.85,
    },
    {
        "rule_id": "PY-SEC-016",
        "name": "Python String Template Injection",
        "description": "string.Template is used with user-controlled template strings, enabling injection via $identifier.",
        "severity": "HIGH",
        "cwe_id": "CWE-94",
        "pattern": r'string\.Template\s*\(\s*(?:request\.|user_|input)',
        "language": "python",
        "category": "INJECTION",
        "recommendation": "Do not use user-supplied data as a Template source. Pre-define templates statically.",
        "confidence": 0.8,
    },

    # Log Injection
    {
        "rule_id": "PY-SEC-017",
        "name": "Log Injection",
        "description": "User-controlled data is written directly to a log statement, enabling log injection or log forging.",
        "severity": "MEDIUM",
        "cwe_id": "CWE-117",
        "pattern": r'(?:logging|logger)\s*\.\s*(?:info|warning|error|debug|critical)\s*\(\s*(?:f["\'].*\{|["\'][^"\']*\+)',
        "language": "python",
        "category": "INJECTION",
        "recommendation": "Strip or escape newline characters (\\r, \\n) from user-controlled data before logging.",
        "confidence": 0.75,
    },

    # NoSQL Injection
    {
        "rule_id": "PY-SEC-018",
        "name": "MongoDB $where Injection",
        "description": "The MongoDB $where operator executes JavaScript server-side and is vulnerable to injection.",
        "severity": "CRITICAL",
        "cwe_id": "CWE-943",
        "pattern": r'\$where\s*:',
        "language": "python",
        "category": "INJECTION",
        "recommendation": "Avoid using $where entirely. Use standard MongoDB query operators instead.",
        "confidence": 0.9,
    },
    {
        "rule_id": "PY-SEC-019",
        "name": "NoSQL Operator Injection",
        "description": "MongoDB query uses user-supplied keys that may contain operators like $ne, $gt, enabling NoSQL injection.",
        "severity": "HIGH",
        "cwe_id": "CWE-943",
        "pattern": r'find(?:_one)?\s*\(\s*(?:request\.|user_data|data\[)',
        "language": "python",
        "category": "INJECTION",
        "recommendation": "Validate and whitelist query keys. Never pass raw user-controlled dicts as MongoDB query filters.",
        "confidence": 0.75,
    },
    {
        "rule_id": "PY-SEC-020",
        "name": "SQLite3 String Formatting Injection",
        "description": "sqlite3 execute() uses string formatting instead of parameter substitution.",
        "severity": "CRITICAL",
        "cwe_id": "CWE-89",
        "pattern": r'sqlite3.*\.execute\s*\(\s*(?:f["\']|["\'][^"\']*%)',
        "language": "python",
        "category": "INJECTION",
        "recommendation": "Use the ? placeholder for sqlite3 parameters: cursor.execute('SELECT * FROM t WHERE x=?', (val,))",
        "confidence": 0.9,
    },
    {
        "rule_id": "PY-SEC-021",
        "name": "psycopg2 Unsafe SQL Composition",
        "description": "psycopg2 query uses Identifier() or format() without proper parameterization.",
        "severity": "HIGH",
        "cwe_id": "CWE-89",
        "pattern": r'psycopg2.*\.execute\s*\(\s*(?:f["\']|["\'][^"\']*%[^(])',
        "language": "python",
        "category": "INJECTION",
        "recommendation": "Use psycopg2.sql module for dynamic identifiers and %s placeholders for values.",
        "confidence": 0.85,
    },
    {
        "rule_id": "PY-SEC-022",
        "name": "Shell Injection via shlex Bypass",
        "description": "shlex.split is used, but the result is still passed to a shell, defeating its purpose.",
        "severity": "HIGH",
        "cwe_id": "CWE-78",
        "pattern": r'subprocess\.\w+\s*\(\s*shlex\.split[^)]*shell\s*=\s*True',
        "language": "python",
        "category": "INJECTION",
        "recommendation": "Remove shell=True when using a list of arguments. shlex.split() is only useful with shell=False.",
        "confidence": 0.85,
    },
    {
        "rule_id": "PY-SEC-023",
        "name": "SSML Injection in TTS Systems",
        "description": "User-supplied text is embedded in SSML markup without escaping, potentially injecting speech commands.",
        "severity": "MEDIUM",
        "cwe_id": "CWE-116",
        "pattern": r'<speak>.*\{|ssml.*f["\'].*\{',
        "language": "python",
        "category": "INJECTION",
        "recommendation": "Escape SSML special characters (<, >, &, \", ') before embedding user data in SSML.",
        "confidence": 0.7,
    },
    {
        "rule_id": "PY-SEC-024",
        "name": "Email Header Injection",
        "description": "User-controlled data is placed in email headers without stripping newline characters.",
        "severity": "HIGH",
        "cwe_id": "CWE-93",
        "pattern": r'(?:smtplib|sendmail|send_mail)\s*.*(?:Subject|From|To|Cc)\s*.*(?:request\.|user_)',
        "language": "python",
        "category": "INJECTION",
        "recommendation": "Strip \\r and \\n characters from all email header values derived from user input.",
        "confidence": 0.75,
    },
    {
        "rule_id": "PY-SEC-025",
        "name": "HTTP Response Splitting",
        "description": "User-controlled data is placed in HTTP response headers without stripping CRLF characters.",
        "severity": "HIGH",
        "cwe_id": "CWE-113",
        "pattern": r'response\[(?:\'|")(?:Location|Set-Cookie|Content-Type)(?:\'|")\]\s*=\s*(?:request\.|user_)',
        "language": "python",
        "category": "INJECTION",
        "recommendation": "Validate and sanitize all header values, removing \\r and \\n sequences.",
        "confidence": 0.8,
    },
    {
        "rule_id": "PY-SEC-026",
        "name": "Format String Injection via % Operator",
        "description": "A format string is constructed from user input and evaluated with %, risking injection or information disclosure.",
        "severity": "HIGH",
        "cwe_id": "CWE-134",
        "pattern": r'(?:request\.(?:args|form|json|data|POST|GET)\[.*\])\s*%\s*\(',
        "language": "python",
        "category": "INJECTION",
        "recommendation": "Do not use user-controlled data as format strings. Use static format strings with user data as arguments.",
        "confidence": 0.85,
    },
    {
        "rule_id": "PY-SEC-027",
        "name": "GraphQL Injection via Raw String",
        "description": "A GraphQL query string is built by concatenating user data, enabling injection of query operators.",
        "severity": "HIGH",
        "cwe_id": "CWE-89",
        "pattern": r'gql\s*\(\s*(?:f["\']|["\'][^"\']*\+)',
        "language": "python",
        "category": "INJECTION",
        "recommendation": "Use GraphQL variables to pass user data rather than embedding it in the query string.",
        "confidence": 0.85,
    },
    {
        "rule_id": "PY-SEC-028",
        "name": "Elasticsearch DSL Injection",
        "description": "An Elasticsearch query is dynamically constructed with user data in the _source or query string.",
        "severity": "HIGH",
        "cwe_id": "CWE-943",
        "pattern": r'elasticsearch.*body\s*=\s*\{[^}]*(?:f["\']|request\.)',
        "language": "python",
        "category": "INJECTION",
        "recommendation": "Validate user inputs against an allowlist before including them in Elasticsearch query bodies.",
        "confidence": 0.75,
    },
    {
        "rule_id": "PY-SEC-029",
        "name": "Redis Command Injection",
        "description": "Redis commands are constructed with user-supplied keys or values without validation.",
        "severity": "HIGH",
        "cwe_id": "CWE-943",
        "pattern": r'redis.*(?:execute_command|eval|evalsha)\s*\(\s*(?:f["\']|[^)]*\+)',
        "language": "python",
        "category": "INJECTION",
        "recommendation": "Validate and sanitize Redis keys. Avoid eval/evalsha with user-controlled scripts.",
        "confidence": 0.8,
    },
    {
        "rule_id": "PY-SEC-030",
        "name": "Celery Task Name Injection",
        "description": "Celery app.send_task() is called with a task name derived from user input, allowing unauthorized task invocation.",
        "severity": "HIGH",
        "cwe_id": "CWE-78",
        "pattern": r'(?:app|celery)\.send_task\s*\(\s*(?:request\.|user_|f["\'])',
        "language": "python",
        "category": "INJECTION",
        "recommendation": "Whitelist allowed task names and validate user input against the whitelist before calling send_task.",
        "confidence": 0.8,
    },

    # =========================================================================
    # CRYPTOGRAPHY (20 rules)  PY-SEC-031 – PY-SEC-050
    # =========================================================================

    {
        "rule_id": "PY-SEC-031",
        "name": "Use of MD5 for Security Purpose",
        "description": "MD5 is a broken hash algorithm and must not be used for password hashing, integrity verification, or HMAC.",
        "severity": "HIGH",
        "cwe_id": "CWE-327",
        "pattern": r'hashlib\.md5\s*\(',
        "language": "python",
        "category": "CRYPTO",
        "recommendation": "Replace MD5 with SHA-256 or SHA-3 for non-password hashing; use bcrypt/argon2 for passwords.",
        "confidence": 0.9,
    },
    {
        "rule_id": "PY-SEC-032",
        "name": "Use of SHA-1 for Security Purpose",
        "description": "SHA-1 is cryptographically broken and should not be used for security-sensitive operations.",
        "severity": "HIGH",
        "cwe_id": "CWE-327",
        "pattern": r'hashlib\.sha1\s*\(',
        "language": "python",
        "category": "CRYPTO",
        "recommendation": "Replace SHA-1 with SHA-256 or higher. If backwards compatibility is needed, plan a migration path.",
        "confidence": 0.9,
    },
    {
        "rule_id": "PY-SEC-033",
        "name": "DES Cipher Usage",
        "description": "DES has a 56-bit key and has been broken since 1999. It must not be used for encryption.",
        "severity": "CRITICAL",
        "cwe_id": "CWE-327",
        "pattern": r'(?:Cipher|algorithms)\.(?:DES|TripleDES)\s*\(',
        "language": "python",
        "category": "CRYPTO",
        "recommendation": "Use AES-256-GCM or ChaCha20-Poly1305 instead.",
        "confidence": 0.95,
    },
    {
        "rule_id": "PY-SEC-034",
        "name": "RC4 Stream Cipher Usage",
        "description": "RC4 is a broken stream cipher with multiple known biases and must not be used.",
        "severity": "CRITICAL",
        "cwe_id": "CWE-327",
        "pattern": r'(?:ARC4|RC4)\s*\(',
        "language": "python",
        "category": "CRYPTO",
        "recommendation": "Replace RC4 with AES-GCM or ChaCha20-Poly1305.",
        "confidence": 0.95,
    },
    {
        "rule_id": "PY-SEC-035",
        "name": "ECB Mode Cipher Usage",
        "description": "ECB mode does not use an IV and encrypts identical plaintext blocks to identical ciphertext, leaking patterns.",
        "severity": "HIGH",
        "cwe_id": "CWE-327",
        "pattern": r'modes\.ECB\s*\(',
        "language": "python",
        "category": "CRYPTO",
        "recommendation": "Use AES-GCM or AES-CBC with a random IV and a MAC for authenticated encryption.",
        "confidence": 0.95,
    },
    {
        "rule_id": "PY-SEC-036",
        "name": "Hardcoded IV or Salt",
        "description": "A static IV or salt defeats the purpose of using one; all IVs and salts must be randomly generated.",
        "severity": "HIGH",
        "cwe_id": "CWE-330",
        "pattern": r'(?:iv|IV|salt|SALT|nonce)\s*=\s*(?:b["\'][^"\']{1,32}["\']|bytes\s*\(\s*[0-9]+\s*\))',
        "language": "python",
        "category": "CRYPTO",
        "recommendation": "Generate IVs and salts with os.urandom() or secrets.token_bytes() for every encryption operation.",
        "confidence": 0.85,
    },
    {
        "rule_id": "PY-SEC-037",
        "name": "Short RSA/DSA Key (< 2048 bits)",
        "description": "Cryptographic keys shorter than 2048 bits for RSA/DSA are considered insecure.",
        "severity": "HIGH",
        "cwe_id": "CWE-326",
        "pattern": r'(?:generate_private_key|rsa\.generate_private_key|generate_parameters)\s*\([^)]*\b(?:512|768|1024)\b',
        "language": "python",
        "category": "CRYPTO",
        "recommendation": "Use a minimum of 2048-bit keys for RSA/DSA; prefer 4096-bit. For elliptic curve, use P-256 or higher.",
        "confidence": 0.95,
    },
    {
        "rule_id": "PY-SEC-038",
        "name": "Insecure Random for Security Purposes",
        "description": "random.random() or random.choice() uses a PRNG not suitable for cryptographic or security purposes.",
        "severity": "HIGH",
        "cwe_id": "CWE-338",
        "pattern": r'random\.(?:random|choice|randint|shuffle|sample|randrange)\s*\(',
        "language": "python",
        "category": "CRYPTO",
        "recommendation": "Use the secrets module (secrets.token_bytes, secrets.choice) for security-sensitive randomness.",
        "confidence": 0.75,
    },
    {
        "rule_id": "PY-SEC-039",
        "name": "Hardcoded Private Key",
        "description": "A PEM-encoded private key is embedded as a string literal in source code.",
        "severity": "CRITICAL",
        "cwe_id": "CWE-321",
        "pattern": r'-----BEGIN (?:RSA |EC |DSA |OPENSSH )?PRIVATE KEY-----',
        "language": "python",
        "category": "CRYPTO",
        "recommendation": "Remove private keys from source. Load them from environment variables or a secrets manager at runtime.",
        "confidence": 0.99,
    },
    {
        "rule_id": "PY-SEC-040",
        "name": "SSL/TLS Certificate Verification Disabled",
        "description": "SSL certificate verification is explicitly disabled (verify=False), making connections vulnerable to MITM.",
        "severity": "HIGH",
        "cwe_id": "CWE-295",
        "pattern": r'(?:requests|urllib3|httpx|aiohttp)\.[^(]*\([^)]*verify\s*=\s*False',
        "language": "python",
        "category": "CRYPTO",
        "recommendation": "Always leave verify=True (the default). If using a private CA, pass the CA bundle path to verify=.",
        "confidence": 0.95,
    },
    {
        "rule_id": "PY-SEC-041",
        "name": "Weak PBKDF2 Iteration Count",
        "description": "PBKDF2 is used with fewer than 260,000 iterations, weakening its resistance to brute force.",
        "severity": "MEDIUM",
        "cwe_id": "CWE-916",
        "pattern": r'pbkdf2_hmac\s*\([^)]*(?:1000|5000|10000|50000)\b',
        "language": "python",
        "category": "CRYPTO",
        "recommendation": "Use at least 260,000 iterations with SHA-256 as recommended by OWASP, or switch to argon2-cffi.",
        "confidence": 0.85,
    },
    {
        "rule_id": "PY-SEC-042",
        "name": "Blowfish Cipher Usage",
        "description": "Blowfish has a 64-bit block size and is vulnerable to birthday attacks (SWEET32). It should not be used.",
        "severity": "HIGH",
        "cwe_id": "CWE-327",
        "pattern": r'algorithms\.Blowfish\s*\(',
        "language": "python",
        "category": "CRYPTO",
        "recommendation": "Replace Blowfish with AES-256-GCM.",
        "confidence": 0.95,
    },
    {
        "rule_id": "PY-SEC-043",
        "name": "MD5 Used in HMAC",
        "description": "HMAC is constructed with MD5, a broken hash algorithm, reducing MAC security.",
        "severity": "HIGH",
        "cwe_id": "CWE-327",
        "pattern": r'hmac\.new\s*\([^)]*(?:md5|MD5)',
        "language": "python",
        "category": "CRYPTO",
        "recommendation": "Use HMAC-SHA-256 or HMAC-SHA-512 instead.",
        "confidence": 0.9,
    },
    {
        "rule_id": "PY-SEC-044",
        "name": "Hardcoded Certificate in Source",
        "description": "A PEM certificate (public or CA) is hardcoded in the source, making rotation difficult.",
        "severity": "MEDIUM",
        "cwe_id": "CWE-798",
        "pattern": r'-----BEGIN CERTIFICATE-----',
        "language": "python",
        "category": "CRYPTO",
        "recommendation": "Store certificates outside of source code and load them from a configurable file path.",
        "confidence": 0.85,
    },
    {
        "rule_id": "PY-SEC-045",
        "name": "SSL PROTOCOL_SSLv2 or PROTOCOL_SSLv3 Usage",
        "description": "SSLv2 and SSLv3 are deprecated and vulnerable to POODLE and other attacks.",
        "severity": "CRITICAL",
        "cwe_id": "CWE-326",
        "pattern": r'ssl\.(?:PROTOCOL_SSLv2|PROTOCOL_SSLv3)\b',
        "language": "python",
        "category": "CRYPTO",
        "recommendation": "Use ssl.PROTOCOL_TLS_CLIENT or ssl.PROTOCOL_TLS_SERVER with minimum_version=TLSVersion.TLSv1_2.",
        "confidence": 0.99,
    },
    {
        "rule_id": "PY-SEC-046",
        "name": "Null Cipher Usage",
        "description": "A null/NoCipher is configured for a TLS connection, meaning data is sent in cleartext.",
        "severity": "CRITICAL",
        "cwe_id": "CWE-327",
        "pattern": r'ssl_version\s*=\s*ssl\.PROTOCOL_SSLv23|cipher_list\s*=\s*["\']NULL',
        "language": "python",
        "category": "CRYPTO",
        "recommendation": "Remove any null cipher configuration. Use strong TLS 1.2/1.3 cipher suites.",
        "confidence": 0.9,
    },
    {
        "rule_id": "PY-SEC-047",
        "name": "Weak Diffie-Hellman Parameters",
        "description": "DH parameter size less than 2048 bits is considered insecure against Logjam attacks.",
        "severity": "HIGH",
        "cwe_id": "CWE-326",
        "pattern": r'dh_parameters_from_primitives\s*\([^)]*(?:512|768|1024)\b',
        "language": "python",
        "category": "CRYPTO",
        "recommendation": "Use DH parameters of at least 2048 bits, or switch to ECDH.",
        "confidence": 0.9,
    },
    {
        "rule_id": "PY-SEC-048",
        "name": "JWT with HS256 and Hardcoded Secret",
        "description": "A JWT is signed with HS256 but the secret is a hardcoded short string, making it easily brutable.",
        "severity": "CRITICAL",
        "cwe_id": "CWE-321",
        "pattern": r'jwt\.encode\s*\([^)]*["\'][a-zA-Z0-9]{1,20}["\']\s*,\s*algorithm\s*=\s*["\']HS256["\']',
        "language": "python",
        "category": "CRYPTO",
        "recommendation": "Use a cryptographically random secret of at least 256 bits, loaded from a secure secrets manager.",
        "confidence": 0.85,
    },
    {
        "rule_id": "PY-SEC-049",
        "name": "Random Seed with Fixed Value",
        "description": "random.seed() is called with a fixed/hardcoded value, making PRNG output deterministic.",
        "severity": "HIGH",
        "cwe_id": "CWE-335",
        "pattern": r'random\.seed\s*\(\s*(?:[0-9]+|["\'])',
        "language": "python",
        "category": "CRYPTO",
        "recommendation": "Do not seed random with a fixed value for security-sensitive contexts. Use secrets module instead.",
        "confidence": 0.85,
    },
    {
        "rule_id": "PY-SEC-050",
        "name": "Cryptography Padding Oracle Risk (CBC + no MAC)",
        "description": "AES-CBC mode is used without an authentication tag or HMAC, making it vulnerable to padding oracle attacks.",
        "severity": "HIGH",
        "cwe_id": "CWE-327",
        "pattern": r'modes\.CBC\s*\(',
        "language": "python",
        "category": "CRYPTO",
        "recommendation": "Switch to AES-GCM which provides both encryption and authentication, or add HMAC-SHA256 over the ciphertext.",
        "confidence": 0.75,
    },

    # =========================================================================
    # AUTHENTICATION / AUTHORIZATION (20 rules)  PY-SEC-051 – PY-SEC-070
    # =========================================================================

    {
        "rule_id": "PY-SEC-051",
        "name": "Hardcoded Password in Source",
        "description": "A password literal is assigned to a variable named with common password-related identifiers.",
        "severity": "CRITICAL",
        "cwe_id": "CWE-798",
        "pattern": r'(?:password|passwd|secret|api_key|apikey|token)\s*=\s*["\'][^"\']{6,}["\']',
        "language": "python",
        "category": "AUTH",
        "recommendation": "Load credentials from environment variables or a secrets manager (e.g., HashiCorp Vault, AWS Secrets Manager).",
        "confidence": 0.85,
    },
    {
        "rule_id": "PY-SEC-052",
        "name": "JWT Decoded Without Signature Verification",
        "description": "jwt.decode() is called with options={'verify_signature': False}, bypassing token validation.",
        "severity": "CRITICAL",
        "cwe_id": "CWE-345",
        "pattern": r'jwt\.decode\s*\([^)]*(?:verify_signature\s*:\s*False|options\s*=\s*\{[^}]*False)',
        "language": "python",
        "category": "AUTH",
        "recommendation": "Always verify the JWT signature. Use a strong signing key and validate all expected claims.",
        "confidence": 0.95,
    },
    {
        "rule_id": "PY-SEC-053",
        "name": "JWT Algorithm Set to None",
        "description": "The JWT algorithm is explicitly set to 'none', meaning no signature is applied or verified.",
        "severity": "CRITICAL",
        "cwe_id": "CWE-345",
        "pattern": r'jwt\.(?:encode|decode)\s*\([^)]*algorithm\s*=\s*["\']none["\']',
        "language": "python",
        "category": "AUTH",
        "recommendation": "Always specify a strong algorithm (e.g., RS256, ES256, HS256 with a secure key).",
        "confidence": 0.99,
    },
    {
        "rule_id": "PY-SEC-054",
        "name": "Django CSRF Protection Disabled",
        "description": "Django's @csrf_exempt decorator disables CSRF protection on a view, making it vulnerable to CSRF attacks.",
        "severity": "HIGH",
        "cwe_id": "CWE-352",
        "pattern": r'@csrf_exempt',
        "language": "python",
        "category": "AUTH",
        "recommendation": "Remove @csrf_exempt and handle CSRF tokens properly. If an API endpoint uses token auth, add appropriate auth checks instead.",
        "confidence": 0.9,
    },
    {
        "rule_id": "PY-SEC-055",
        "name": "Flask Session Secret Key Hardcoded",
        "description": "Flask app.secret_key is set to a hardcoded literal, enabling session forgery.",
        "severity": "CRITICAL",
        "cwe_id": "CWE-798",
        "pattern": r'(?:app|application)\.secret_key\s*=\s*["\'][^"\']+["\']',
        "language": "python",
        "category": "AUTH",
        "recommendation": "Set secret_key from an environment variable: app.secret_key = os.environ['SECRET_KEY']",
        "confidence": 0.9,
    },
    {
        "rule_id": "PY-SEC-056",
        "name": "Insecure Session Cookie Configuration",
        "description": "Session cookie is missing HttpOnly or Secure flags, making it accessible to JavaScript or transmitted over HTTP.",
        "severity": "HIGH",
        "cwe_id": "CWE-614",
        "pattern": r'SESSION_COOKIE_(?:HTTPONLY|SECURE)\s*=\s*False',
        "language": "python",
        "category": "AUTH",
        "recommendation": "Set SESSION_COOKIE_HTTPONLY=True and SESSION_COOKIE_SECURE=True in Django/Flask settings.",
        "confidence": 0.95,
    },
    {
        "rule_id": "PY-SEC-057",
        "name": "Authentication Bypass via Empty Password Check",
        "description": "An authentication check compares the password to an empty string, which may always match or be bypassed.",
        "severity": "CRITICAL",
        "cwe_id": "CWE-287",
        "pattern": r'(?:password|passwd)\s*==\s*["\']["\']',
        "language": "python",
        "category": "AUTH",
        "recommendation": "Use constant-time comparison (hmac.compare_digest) and ensure passwords are never empty.",
        "confidence": 0.9,
    },
    {
        "rule_id": "PY-SEC-058",
        "name": "Timing Attack via == Comparison for Secrets",
        "description": "Secret tokens or passwords are compared using the == operator, which is vulnerable to timing attacks.",
        "severity": "HIGH",
        "cwe_id": "CWE-208",
        "pattern": r'(?:token|secret|api_key|password)\s*==\s*(?:request\.|user_|provided_)',
        "language": "python",
        "category": "AUTH",
        "recommendation": "Use hmac.compare_digest() or secrets.compare_digest() for constant-time comparison of secrets.",
        "confidence": 0.8,
    },
    {
        "rule_id": "PY-SEC-059",
        "name": "Insecure Direct Object Reference",
        "description": "An object is fetched directly using a user-supplied ID without authorization checks.",
        "severity": "HIGH",
        "cwe_id": "CWE-639",
        "pattern": r'(?:get_object_or_404|Model\.objects\.get|find_by_id)\s*\([^)]*(?:request\.|pk\s*=\s*request\.|id\s*=\s*request\.)',
        "language": "python",
        "category": "AUTH",
        "recommendation": "After fetching the object, verify the current user has permission to access it.",
        "confidence": 0.75,
    },
    {
        "rule_id": "PY-SEC-060",
        "name": "Privilege Escalation via User-Controlled Role",
        "description": "A user's role or permission level is set directly from request data without server-side validation.",
        "severity": "CRITICAL",
        "cwe_id": "CWE-269",
        "pattern": r'(?:user\.role|user\.is_admin|user\.is_staff|user\.permissions)\s*=\s*request\.',
        "language": "python",
        "category": "AUTH",
        "recommendation": "Never set roles or privileges from user-supplied data. Apply role changes through administrator-controlled workflows.",
        "confidence": 0.9,
    },
    {
        "rule_id": "PY-SEC-061",
        "name": "Password Stored in Plaintext",
        "description": "A password value is stored in the database or cache without hashing.",
        "severity": "CRITICAL",
        "cwe_id": "CWE-256",
        "pattern": r'(?:user\.password|User\.password)\s*=\s*(?:request\.|password\b)(?!.*hash)',
        "language": "python",
        "category": "AUTH",
        "recommendation": "Always hash passwords with bcrypt, argon2, or Django's make_password() before storing.",
        "confidence": 0.8,
    },
    {
        "rule_id": "PY-SEC-062",
        "name": "Missing @login_required Decorator",
        "description": "A Django view function modifies data but lacks the @login_required decorator.",
        "severity": "HIGH",
        "cwe_id": "CWE-306",
        "pattern": r'^def (?:create|update|delete|edit|save|post)_\w+\s*\(\s*request',
        "language": "python",
        "category": "AUTH",
        "recommendation": "Add @login_required to all views that perform state-changing operations.",
        "confidence": 0.6,
    },
    {
        "rule_id": "PY-SEC-063",
        "name": "Hardcoded API Key",
        "description": "An API key is hardcoded as a string literal in the source code.",
        "severity": "CRITICAL",
        "cwe_id": "CWE-798",
        "pattern": r'(?:api_key|API_KEY|apikey|APIKEY)\s*=\s*["\'][A-Za-z0-9_\-]{20,}["\']',
        "language": "python",
        "category": "AUTH",
        "recommendation": "Store API keys in environment variables or a secrets manager. Never commit keys to version control.",
        "confidence": 0.85,
    },
    {
        "rule_id": "PY-SEC-064",
        "name": "Debug Mode Enabled in Production Setting",
        "description": "DEBUG=True is set in a configuration file that appears to be for production use.",
        "severity": "HIGH",
        "cwe_id": "CWE-489",
        "pattern": r'DEBUG\s*=\s*True',
        "language": "python",
        "category": "AUTH",
        "recommendation": "Set DEBUG=False in production. Use environment-specific configuration files.",
        "confidence": 0.8,
    },
    {
        "rule_id": "PY-SEC-065",
        "name": "Cookie Without SameSite Attribute",
        "description": "A cookie is set without the SameSite attribute, which helps prevent CSRF attacks.",
        "severity": "MEDIUM",
        "cwe_id": "CWE-352",
        "pattern": r'set_cookie\s*\([^)]*(?!samesite)',
        "language": "python",
        "category": "AUTH",
        "recommendation": "Set samesite='Lax' or samesite='Strict' on all cookies to reduce CSRF risk.",
        "confidence": 0.65,
    },
    {
        "rule_id": "PY-SEC-066",
        "name": "Hardcoded Database Credentials",
        "description": "Database username and password are hardcoded in the settings or configuration file.",
        "severity": "CRITICAL",
        "cwe_id": "CWE-798",
        "pattern": r'(?:DB_PASSWORD|DATABASE_PASSWORD|db_pass)\s*=\s*["\'][^"\']+["\']',
        "language": "python",
        "category": "AUTH",
        "recommendation": "Load database credentials from environment variables or a secrets manager.",
        "confidence": 0.9,
    },
    {
        "rule_id": "PY-SEC-067",
        "name": "Basic Auth Credentials in URL",
        "description": "HTTP Basic Auth credentials are embedded in a URL string, risking exposure in logs and history.",
        "severity": "HIGH",
        "cwe_id": "CWE-522",
        "pattern": r'https?://[^:@\s]+:[^@\s]+@',
        "language": "python",
        "category": "AUTH",
        "recommendation": "Use the auth= parameter of requests.get() or set the Authorization header separately.",
        "confidence": 0.9,
    },
    {
        "rule_id": "PY-SEC-068",
        "name": "Session Fixation Risk",
        "description": "Session ID is not regenerated after a user logs in, which can allow session fixation attacks.",
        "severity": "HIGH",
        "cwe_id": "CWE-384",
        "pattern": r'session\[(?:\'|")user(?:_id|name)?(?:\'|")\]\s*=',
        "language": "python",
        "category": "AUTH",
        "recommendation": "Call session.clear() and regenerate the session ID after successful authentication.",
        "confidence": 0.65,
    },
    {
        "rule_id": "PY-SEC-069",
        "name": "OAuth State Parameter Missing",
        "description": "OAuth flow does not use a state parameter, making it vulnerable to CSRF attacks during authorization.",
        "severity": "HIGH",
        "cwe_id": "CWE-352",
        "pattern": r'oauth\.(?:authorize_url|redirect_to_provider)\s*\([^)]*(?!state)',
        "language": "python",
        "category": "AUTH",
        "recommendation": "Always include a random state parameter in OAuth authorization requests and verify it on callback.",
        "confidence": 0.7,
    },
    {
        "rule_id": "PY-SEC-070",
        "name": "Hardcoded AWS Secret Access Key",
        "description": "An AWS secret access key is hardcoded as a string literal.",
        "severity": "CRITICAL",
        "cwe_id": "CWE-798",
        "pattern": r'(?:aws_secret_access_key|AWS_SECRET_ACCESS_KEY)\s*=\s*["\'][A-Za-z0-9/+=]{40}["\']',
        "language": "python",
        "category": "AUTH",
        "recommendation": "Use IAM instance roles, environment variables, or AWS Secrets Manager instead of hardcoded keys.",
        "confidence": 0.95,
    },

    # =========================================================================
    # DESERIALIZATION (10 rules)  PY-SEC-071 – PY-SEC-080
    # =========================================================================

    {
        "rule_id": "PY-SEC-071",
        "name": "Unsafe pickle.loads",
        "description": "pickle.loads() deserializes untrusted data; malicious pickle payloads can execute arbitrary code.",
        "severity": "CRITICAL",
        "cwe_id": "CWE-502",
        "pattern": r'pickle\.loads?\s*\(',
        "language": "python",
        "category": "DESERIALIZATION",
        "recommendation": "Never deserialize untrusted data with pickle. Use json or another safe format.",
        "confidence": 0.9,
    },
    {
        "rule_id": "PY-SEC-072",
        "name": "yaml.load Without Safe Loader",
        "description": "yaml.load() without Loader=yaml.SafeLoader can execute arbitrary Python code via YAML tags.",
        "severity": "CRITICAL",
        "cwe_id": "CWE-502",
        "pattern": r'yaml\.load\s*\([^)]*(?!\bSafeLoader\b|\bBaseLoader\b)',
        "language": "python",
        "category": "DESERIALIZATION",
        "recommendation": "Use yaml.safe_load() or yaml.load(data, Loader=yaml.SafeLoader).",
        "confidence": 0.9,
    },
    {
        "rule_id": "PY-SEC-073",
        "name": "marshal.loads Usage",
        "description": "marshal.loads() is inherently unsafe for untrusted data; it can cause crashes and arbitrary code execution.",
        "severity": "CRITICAL",
        "cwe_id": "CWE-502",
        "pattern": r'marshal\.loads?\s*\(',
        "language": "python",
        "category": "DESERIALIZATION",
        "recommendation": "Do not deserialize user-supplied data with marshal. Use json or a validated schema instead.",
        "confidence": 0.9,
    },
    {
        "rule_id": "PY-SEC-074",
        "name": "jsonpickle Deserialization",
        "description": "jsonpickle.decode() can execute arbitrary Python code embedded in the JSON payload.",
        "severity": "CRITICAL",
        "cwe_id": "CWE-502",
        "pattern": r'jsonpickle\.decode\s*\(',
        "language": "python",
        "category": "DESERIALIZATION",
        "recommendation": "Avoid jsonpickle for untrusted input. Use json.loads() with a strict schema validation step.",
        "confidence": 0.95,
    },
    {
        "rule_id": "PY-SEC-075",
        "name": "shelve With User-Controlled Key",
        "description": "shelve opens a dbm file using a user-controlled key, which can be exploited for path traversal or data injection.",
        "severity": "HIGH",
        "cwe_id": "CWE-502",
        "pattern": r'shelve\.open\s*\(\s*(?:request\.|user_|f["\'])',
        "language": "python",
        "category": "DESERIALIZATION",
        "recommendation": "Never use user-controlled data as a shelve key or filename. Whitelist allowed key values.",
        "confidence": 0.85,
    },
    {
        "rule_id": "PY-SEC-076",
        "name": "eval() With User Data",
        "description": "eval() evaluates a Python expression from user-controlled data, allowing arbitrary code execution.",
        "severity": "CRITICAL",
        "cwe_id": "CWE-95",
        "pattern": r'eval\s*\(\s*(?:request\.|user_|input\(|f["\'])',
        "language": "python",
        "category": "DESERIALIZATION",
        "recommendation": "Never pass user input to eval(). Use ast.literal_eval() for safe evaluation of literals.",
        "confidence": 0.95,
    },
    {
        "rule_id": "PY-SEC-077",
        "name": "exec() With User Data",
        "description": "exec() executes arbitrary Python code from user-controlled data.",
        "severity": "CRITICAL",
        "cwe_id": "CWE-95",
        "pattern": r'exec\s*\(\s*(?:request\.|user_|input\(|f["\'])',
        "language": "python",
        "category": "DESERIALIZATION",
        "recommendation": "Remove all exec() calls that involve user data. Refactor to use safe, data-driven logic.",
        "confidence": 0.95,
    },
    {
        "rule_id": "PY-SEC-078",
        "name": "cPickle Usage",
        "description": "cPickle (Python 2) or _pickle is equally unsafe to pickle when used with untrusted data.",
        "severity": "CRITICAL",
        "cwe_id": "CWE-502",
        "pattern": r'(?:cPickle|_pickle)\.loads?\s*\(',
        "language": "python",
        "category": "DESERIALIZATION",
        "recommendation": "Do not deserialize untrusted data with cPickle. Use json with schema validation.",
        "confidence": 0.95,
    },
    {
        "rule_id": "PY-SEC-079",
        "name": "Dill Deserialization",
        "description": "dill.loads() extends pickle and can deserialize and execute arbitrary Python objects.",
        "severity": "CRITICAL",
        "cwe_id": "CWE-502",
        "pattern": r'dill\.loads?\s*\(',
        "language": "python",
        "category": "DESERIALIZATION",
        "recommendation": "Avoid dill for untrusted data. Restrict use to trusted internal serialization only.",
        "confidence": 0.9,
    },
    {
        "rule_id": "PY-SEC-080",
        "name": "Unsafe TOML Load from User Data",
        "description": "toml.loads() or tomllib.loads() with user-supplied content may expose server internals.",
        "severity": "MEDIUM",
        "cwe_id": "CWE-20",
        "pattern": r'toml(?:lib)?\.loads?\s*\(\s*(?:request\.|user_)',
        "language": "python",
        "category": "DESERIALIZATION",
        "recommendation": "Validate TOML input against a strict schema before processing. Limit accepted keys.",
        "confidence": 0.75,
    },

    # =========================================================================
    # FILE / PATH OPERATIONS (15 rules)  PY-SEC-081 – PY-SEC-095
    # =========================================================================

    {
        "rule_id": "PY-SEC-081",
        "name": "Path Traversal via os.path.join with User Input",
        "description": "os.path.join() is called with user-supplied data, and the result is used to open a file, enabling path traversal.",
        "severity": "HIGH",
        "cwe_id": "CWE-22",
        "pattern": r'os\.path\.join\s*\([^)]*(?:request\.|user_|f["\'])',
        "language": "python",
        "category": "FILE",
        "recommendation": "Resolve the final path with os.path.realpath() and verify it starts with the expected base directory.",
        "confidence": 0.85,
    },
    {
        "rule_id": "PY-SEC-082",
        "name": "Arbitrary File Write via User-Controlled Path",
        "description": "open() is called in write mode with a filename derived from user input, enabling arbitrary file write.",
        "severity": "CRITICAL",
        "cwe_id": "CWE-73",
        "pattern": r'open\s*\(\s*(?:request\.|user_|f["\'][^"\']*\{)[^)]*["\']w["\']',
        "language": "python",
        "category": "FILE",
        "recommendation": "Validate and sanitize file paths. Use a whitelist of allowed directories and filenames.",
        "confidence": 0.85,
    },
    {
        "rule_id": "PY-SEC-083",
        "name": "Insecure Temporary File Creation (tempfile.mktemp)",
        "description": "tempfile.mktemp() returns a filename but does not create the file atomically, creating a TOCTOU race.",
        "severity": "HIGH",
        "cwe_id": "CWE-377",
        "pattern": r'tempfile\.mktemp\s*\(',
        "language": "python",
        "category": "FILE",
        "recommendation": "Use tempfile.mkstemp() or tempfile.NamedTemporaryFile() which create the file atomically.",
        "confidence": 0.95,
    },
    {
        "rule_id": "PY-SEC-084",
        "name": "Zipfile Extraction Without Path Validation (Zip Slip)",
        "description": "ZipFile.extractall() or extract() is used without verifying that extracted paths stay within the target directory.",
        "severity": "HIGH",
        "cwe_id": "CWE-22",
        "pattern": r'(?:ZipFile|zipfile\.ZipFile)\s*\([^)]*\).*\.(?:extractall|extract)\s*\(',
        "language": "python",
        "category": "FILE",
        "recommendation": "Validate each member path with os.path.realpath() before extraction to prevent Zip Slip.",
        "confidence": 0.8,
    },
    {
        "rule_id": "PY-SEC-085",
        "name": "Tarfile Extraction Without Path Validation",
        "description": "tarfile.extractall() can extract files outside the target directory if member names contain '..'.",
        "severity": "HIGH",
        "cwe_id": "CWE-22",
        "pattern": r'tarfile\.open\s*\([^)]*\).*\.extractall\s*\(',
        "language": "python",
        "category": "FILE",
        "recommendation": "Check each tarinfo.name with os.path.realpath() before extraction.",
        "confidence": 0.8,
    },
    {
        "rule_id": "PY-SEC-086",
        "name": "Symlink Following Attack",
        "description": "A file is opened after checking if it exists, but before opening it could be replaced with a symlink.",
        "severity": "HIGH",
        "cwe_id": "CWE-61",
        "pattern": r'os\.path\.exists\s*\([^)]*\)\s*.*open\s*\(',
        "language": "python",
        "category": "FILE",
        "recommendation": "Use os.open() with O_NOFOLLOW flag to prevent symlink following, or use pathlib with follow_symlinks=False.",
        "confidence": 0.65,
    },
    {
        "rule_id": "PY-SEC-087",
        "name": "File Read with User-Controlled Path",
        "description": "open() or Path.read_text() is called with a path from user input, enabling path traversal to read arbitrary files.",
        "severity": "HIGH",
        "cwe_id": "CWE-22",
        "pattern": r'open\s*\(\s*(?:request\.|user_path|user_file)',
        "language": "python",
        "category": "FILE",
        "recommendation": "Validate the resolved path is within the allowed directory using Path.resolve().",
        "confidence": 0.85,
    },
    {
        "rule_id": "PY-SEC-088",
        "name": "Hardcoded Absolute Path in File Operation",
        "description": "A hardcoded absolute path is used in a file operation, which may reveal directory structure.",
        "severity": "LOW",
        "cwe_id": "CWE-200",
        "pattern": r'open\s*\(\s*["\'](?:/etc/|/var/|/home/|C:\\\\)',
        "language": "python",
        "category": "FILE",
        "recommendation": "Use configurable base directories and relative paths instead of hardcoded absolute paths.",
        "confidence": 0.7,
    },
    {
        "rule_id": "PY-SEC-089",
        "name": "World-Writable File Permission",
        "description": "A file or directory is created with 0o777 permissions, making it writable by all users.",
        "severity": "HIGH",
        "cwe_id": "CWE-732",
        "pattern": r'os\.(?:chmod|makedirs|mkdir)\s*\([^)]*0o777',
        "language": "python",
        "category": "FILE",
        "recommendation": "Use restrictive permissions (0o600 for files, 0o700 for directories) and avoid 0o777.",
        "confidence": 0.9,
    },
    {
        "rule_id": "PY-SEC-090",
        "name": "Unsafe use of os.remove with User Path",
        "description": "os.remove() or os.unlink() is called with a path derived from user input, enabling arbitrary file deletion.",
        "severity": "CRITICAL",
        "cwe_id": "CWE-73",
        "pattern": r'os\.(?:remove|unlink)\s*\(\s*(?:request\.|user_)',
        "language": "python",
        "category": "FILE",
        "recommendation": "Whitelist allowed paths and verify the resolved path is within the expected directory before deletion.",
        "confidence": 0.85,
    },
    {
        "rule_id": "PY-SEC-091",
        "name": "Path Traversal via send_file",
        "description": "Flask's send_file() is called with a user-supplied path, which can expose arbitrary files.",
        "severity": "CRITICAL",
        "cwe_id": "CWE-22",
        "pattern": r'send_file\s*\(\s*(?:request\.|user_)',
        "language": "python",
        "category": "FILE",
        "recommendation": "Use send_from_directory() with a fixed directory parameter. Validate that the filename contains no path separators.",
        "confidence": 0.9,
    },
    {
        "rule_id": "PY-SEC-092",
        "name": "Insecure File Upload Without MIME Validation",
        "description": "An uploaded file is saved without validating the MIME type or file extension, enabling malicious file uploads.",
        "severity": "HIGH",
        "cwe_id": "CWE-434",
        "pattern": r'request\.files\[.*\]\.save\s*\(',
        "language": "python",
        "category": "FILE",
        "recommendation": "Validate the file extension against a whitelist and verify the MIME type using python-magic.",
        "confidence": 0.8,
    },
    {
        "rule_id": "PY-SEC-093",
        "name": "Directory Traversal via pathlib",
        "description": "pathlib.Path is constructed with user input without resolving and validating the result.",
        "severity": "HIGH",
        "cwe_id": "CWE-22",
        "pattern": r'Path\s*\(\s*(?:request\.|user_)',
        "language": "python",
        "category": "FILE",
        "recommendation": "After constructing a Path, call .resolve() and verify it is a child of the expected base directory.",
        "confidence": 0.8,
    },
    {
        "rule_id": "PY-SEC-094",
        "name": "Log File Written to User-Controlled Location",
        "description": "Logging is configured to write to a path derived from user input, enabling log injection or traversal.",
        "severity": "HIGH",
        "cwe_id": "CWE-73",
        "pattern": r'FileHandler\s*\(\s*(?:request\.|user_|f["\'])',
        "language": "python",
        "category": "FILE",
        "recommendation": "Use a fixed log file path defined in server-side configuration only.",
        "confidence": 0.8,
    },
    {
        "rule_id": "PY-SEC-095",
        "name": "CSV Injection in File Export",
        "description": "User data is written to a CSV file without escaping formula injection characters (=, +, -, @).",
        "severity": "MEDIUM",
        "cwe_id": "CWE-1236",
        "pattern": r'csv\.writer\s*\(.*\).*\.writerow\s*\(\s*(?:user_|request\.)',
        "language": "python",
        "category": "FILE",
        "recommendation": "Prefix user-supplied values starting with =, +, -, or @ with a single quote before writing to CSV.",
        "confidence": 0.75,
    },

    # =========================================================================
    # NETWORK / SSRF (15 rules)  PY-SEC-096 – PY-SEC-110
    # =========================================================================

    {
        "rule_id": "PY-SEC-096",
        "name": "SSRF via requests.get with User URL",
        "description": "requests.get() or similar is called with a URL derived from user input, enabling Server-Side Request Forgery.",
        "severity": "CRITICAL",
        "cwe_id": "CWE-918",
        "pattern": r'requests\.\w+\s*\(\s*(?:request\.|user_url|url\s*=\s*request\.)',
        "language": "python",
        "category": "SSRF",
        "recommendation": "Validate URLs against an allowlist of trusted hosts. Reject private/internal IP ranges.",
        "confidence": 0.85,
    },
    {
        "rule_id": "PY-SEC-097",
        "name": "SSRF via urllib with User URL",
        "description": "urllib.request.urlopen() is called with a user-controlled URL, enabling SSRF.",
        "severity": "CRITICAL",
        "cwe_id": "CWE-918",
        "pattern": r'urllib\.request\.urlopen\s*\(\s*(?:request\.|user_)',
        "language": "python",
        "category": "SSRF",
        "recommendation": "Validate the URL scheme and host against a strict allowlist before making the request.",
        "confidence": 0.85,
    },
    {
        "rule_id": "PY-SEC-098",
        "name": "SSRF via httpx with User URL",
        "description": "httpx.get() or httpx.AsyncClient() is called with a user-controlled URL.",
        "severity": "CRITICAL",
        "cwe_id": "CWE-918",
        "pattern": r'httpx\.(?:get|post|put|delete|request|AsyncClient)\s*\(\s*(?:request\.|user_)',
        "language": "python",
        "category": "SSRF",
        "recommendation": "Allowlist target hosts and reject requests to private IP ranges and loopback addresses.",
        "confidence": 0.85,
    },
    {
        "rule_id": "PY-SEC-099",
        "name": "Unvalidated Redirect",
        "description": "An HTTP redirect is performed to a URL taken from user input without validation.",
        "severity": "HIGH",
        "cwe_id": "CWE-601",
        "pattern": r'(?:redirect|HttpResponseRedirect|redirect_to)\s*\(\s*(?:request\.(?:GET|POST|args)\[|next\s*=)',
        "language": "python",
        "category": "SSRF",
        "recommendation": "Validate redirect URLs against a whitelist of allowed paths/domains. Use url_has_allowed_host_and_scheme().",
        "confidence": 0.85,
    },
    {
        "rule_id": "PY-SEC-100",
        "name": "DNS Rebinding Risk via Long-Lived Connection",
        "description": "A request is made to a user-supplied hostname without re-validating the resolved IP, enabling DNS rebinding.",
        "severity": "HIGH",
        "cwe_id": "CWE-350",
        "pattern": r'socket\.gethostbyname\s*\(\s*(?:request\.|user_)',
        "language": "python",
        "category": "SSRF",
        "recommendation": "Resolve the hostname to an IP, block private ranges, then connect by IP—do not rely on hostname after resolution.",
        "confidence": 0.75,
    },
    {
        "rule_id": "PY-SEC-101",
        "name": "SSRF via aiohttp with User URL",
        "description": "aiohttp.ClientSession().get() is called with a user-controlled URL, enabling SSRF in async code.",
        "severity": "CRITICAL",
        "cwe_id": "CWE-918",
        "pattern": r'aiohttp.*(?:get|post|request)\s*\(\s*(?:request\.|user_)',
        "language": "python",
        "category": "SSRF",
        "recommendation": "Validate URLs against an allowlist of trusted hosts before making async HTTP requests.",
        "confidence": 0.85,
    },
    {
        "rule_id": "PY-SEC-102",
        "name": "Open Proxy Pattern",
        "description": "The application blindly forwards HTTP requests to arbitrary URLs specified by the client.",
        "severity": "CRITICAL",
        "cwe_id": "CWE-918",
        "pattern": r'(?:proxy|forward)\s*\(\s*(?:request\.|url\s*=\s*request\.)',
        "language": "python",
        "category": "SSRF",
        "recommendation": "Disallow open proxying. Explicitly enumerate and validate all permitted upstream endpoints.",
        "confidence": 0.8,
    },
    {
        "rule_id": "PY-SEC-103",
        "name": "HTTP Request via User-Supplied Headers",
        "description": "User-controlled data is placed in request headers sent to a backend service, enabling header injection.",
        "severity": "HIGH",
        "cwe_id": "CWE-113",
        "pattern": r'headers\s*=\s*\{[^}]*(?:request\.|user_)',
        "language": "python",
        "category": "SSRF",
        "recommendation": "Build headers from a fixed allowlist. Never copy untrusted request headers to backend requests.",
        "confidence": 0.75,
    },
    {
        "rule_id": "PY-SEC-104",
        "name": "XML RPC with User URL",
        "description": "xmlrpc.client.ServerProxy is called with a URL from user input, enabling SSRF.",
        "severity": "HIGH",
        "cwe_id": "CWE-918",
        "pattern": r'xmlrpc\.client\.ServerProxy\s*\(\s*(?:request\.|user_)',
        "language": "python",
        "category": "SSRF",
        "recommendation": "Allowlist permitted XML-RPC server URLs and never accept them from user input.",
        "confidence": 0.85,
    },
    {
        "rule_id": "PY-SEC-105",
        "name": "SSRF via Webhook Registration",
        "description": "A user-supplied URL is stored as a webhook endpoint and called by the server, enabling SSRF.",
        "severity": "HIGH",
        "cwe_id": "CWE-918",
        "pattern": r'webhook_url\s*=\s*(?:request\.|user_|data\[)',
        "language": "python",
        "category": "SSRF",
        "recommendation": "Validate webhook URLs against an allowlist and block private IP ranges, loopback addresses, and non-HTTP(S) schemes.",
        "confidence": 0.8,
    },
    {
        "rule_id": "PY-SEC-106",
        "name": "FTP Connection to User-Specified Host",
        "description": "ftplib.FTP is instantiated with a user-supplied host, enabling SSRF via FTP.",
        "severity": "HIGH",
        "cwe_id": "CWE-918",
        "pattern": r'ftplib\.FTP\s*\(\s*(?:request\.|user_)',
        "language": "python",
        "category": "SSRF",
        "recommendation": "Only connect to pre-configured FTP hosts. Never accept FTP host from user input.",
        "confidence": 0.85,
    },
    {
        "rule_id": "PY-SEC-107",
        "name": "LDAP Connection to User-Specified Server",
        "description": "An LDAP server address is taken from user input, enabling SSRF or connection to a malicious LDAP server.",
        "severity": "HIGH",
        "cwe_id": "CWE-918",
        "pattern": r'ldap(?:3)?\.(?:Connection|initialize)\s*\(\s*(?:request\.|user_)',
        "language": "python",
        "category": "SSRF",
        "recommendation": "Hardcode the LDAP server in configuration. Do not accept LDAP server addresses from users.",
        "confidence": 0.85,
    },
    {
        "rule_id": "PY-SEC-108",
        "name": "HTTP Instead of HTTPS for External API",
        "description": "An external service is accessed over plain HTTP, allowing traffic interception.",
        "severity": "MEDIUM",
        "cwe_id": "CWE-319",
        "pattern": r'requests\.\w+\s*\(\s*["\']http://',
        "language": "python",
        "category": "SSRF",
        "recommendation": "Use HTTPS for all external API calls. Update URL to https://.",
        "confidence": 0.8,
    },
    {
        "rule_id": "PY-SEC-109",
        "name": "Tornado Fetch with User URL",
        "description": "tornado.httpclient.AsyncHTTPClient.fetch() is called with a user-controlled URL.",
        "severity": "CRITICAL",
        "cwe_id": "CWE-918",
        "pattern": r'(?:AsyncHTTPClient|HTTPClient)\(\)\.fetch\s*\(\s*(?:request\.|user_)',
        "language": "python",
        "category": "SSRF",
        "recommendation": "Validate URLs against an allowlist. Block requests to private IP ranges and non-HTTP schemes.",
        "confidence": 0.85,
    },
    {
        "rule_id": "PY-SEC-110",
        "name": "SSRF via boto3 with User-Controlled Endpoint",
        "description": "A boto3 client is created with an endpoint_url from user input, redirecting AWS API calls to an attacker-controlled server.",
        "severity": "CRITICAL",
        "cwe_id": "CWE-918",
        "pattern": r'boto3\.client\s*\([^)]*endpoint_url\s*=\s*(?:request\.|user_)',
        "language": "python",
        "category": "SSRF",
        "recommendation": "Never accept endpoint_url from user input. Use the default AWS endpoint or configure it via environment variables.",
        "confidence": 0.9,
    },

    # =========================================================================
    # CODE EXECUTION (10 rules)  PY-SEC-111 – PY-SEC-120
    # =========================================================================

    {
        "rule_id": "PY-SEC-111",
        "name": "eval() Arbitrary Code Execution",
        "description": "eval() is called with data that may be user-controlled, enabling arbitrary Python code execution.",
        "severity": "CRITICAL",
        "cwe_id": "CWE-95",
        "pattern": r'\beval\s*\(',
        "language": "python",
        "category": "CODE_EXECUTION",
        "recommendation": "Avoid eval() entirely. Use ast.literal_eval() for literals or define an explicit DSL.",
        "confidence": 0.85,
    },
    {
        "rule_id": "PY-SEC-112",
        "name": "exec() Arbitrary Code Execution",
        "description": "exec() is called with potentially user-controlled data, enabling arbitrary code execution.",
        "severity": "CRITICAL",
        "cwe_id": "CWE-95",
        "pattern": r'\bexec\s*\(',
        "language": "python",
        "category": "CODE_EXECUTION",
        "recommendation": "Remove exec() calls. Implement functionality using safe, data-driven logic.",
        "confidence": 0.85,
    },
    {
        "rule_id": "PY-SEC-113",
        "name": "compile() With User Data",
        "description": "compile() builds executable code from user input, which exec() or eval() then runs.",
        "severity": "CRITICAL",
        "cwe_id": "CWE-95",
        "pattern": r'compile\s*\(\s*(?:request\.|user_|input\()',
        "language": "python",
        "category": "CODE_EXECUTION",
        "recommendation": "Do not compile code from user-supplied strings. Use a sandboxed interpreter if dynamic evaluation is required.",
        "confidence": 0.9,
    },
    {
        "rule_id": "PY-SEC-114",
        "name": "importlib.import_module With User Data",
        "description": "importlib.import_module() loads a module whose name is derived from user input, enabling code execution.",
        "severity": "CRITICAL",
        "cwe_id": "CWE-95",
        "pattern": r'importlib\.import_module\s*\(\s*(?:request\.|user_)',
        "language": "python",
        "category": "CODE_EXECUTION",
        "recommendation": "Whitelist module names that are permitted to be imported dynamically.",
        "confidence": 0.9,
    },
    {
        "rule_id": "PY-SEC-115",
        "name": "__import__ With User Data",
        "description": "__import__() is called with a user-controlled module name, enabling loading of arbitrary modules.",
        "severity": "CRITICAL",
        "cwe_id": "CWE-95",
        "pattern": r'__import__\s*\(\s*(?:request\.|user_)',
        "language": "python",
        "category": "CODE_EXECUTION",
        "recommendation": "Use a strict allowlist of permitted module names when dynamic import is required.",
        "confidence": 0.9,
    },
    {
        "rule_id": "PY-SEC-116",
        "name": "Unrestricted getattr on User-Controlled Name",
        "description": "getattr() is called with an attribute name from user input, enabling access to arbitrary object attributes.",
        "severity": "HIGH",
        "cwe_id": "CWE-470",
        "pattern": r'getattr\s*\([^,]+,\s*(?:request\.|user_)',
        "language": "python",
        "category": "CODE_EXECUTION",
        "recommendation": "Validate the attribute name against a whitelist before calling getattr().",
        "confidence": 0.85,
    },
    {
        "rule_id": "PY-SEC-117",
        "name": "Function Dispatch via User-Controlled Name",
        "description": "globals() or locals() is used to dispatch a function by a name derived from user input.",
        "severity": "HIGH",
        "cwe_id": "CWE-470",
        "pattern": r'(?:globals|locals)\s*\(\s*\)\s*\[\s*(?:request\.|user_)',
        "language": "python",
        "category": "CODE_EXECUTION",
        "recommendation": "Use an explicit dispatch dictionary mapping allowed names to functions.",
        "confidence": 0.9,
    },
    {
        "rule_id": "PY-SEC-118",
        "name": "Jinja2 Template Evaluated with User Code",
        "description": "Jinja2's Environment.from_string() or Template() evaluates user-provided template code, enabling SSTI.",
        "severity": "CRITICAL",
        "cwe_id": "CWE-94",
        "pattern": r'Environment\.from_string\s*\(\s*(?:request\.|user_)',
        "language": "python",
        "category": "CODE_EXECUTION",
        "recommendation": "Use SandboxedEnvironment and static template files. Never accept template code from users.",
        "confidence": 0.95,
    },
    {
        "rule_id": "PY-SEC-119",
        "name": "Celery Task with eval'd Arguments",
        "description": "Celery task arguments are deserialized with eval(), allowing remote code execution.",
        "severity": "CRITICAL",
        "cwe_id": "CWE-95",
        "pattern": r'@app\.task.*\n.*eval\s*\(',
        "language": "python",
        "category": "CODE_EXECUTION",
        "recommendation": "Never call eval() inside Celery tasks. Validate and type-check all task arguments.",
        "confidence": 0.8,
    },
    {
        "rule_id": "PY-SEC-120",
        "name": "Restricted Python Sandbox Escape",
        "description": "Usage of __class__, __mro__, or __subclasses__ on user-controlled objects to escape sandboxes.",
        "severity": "CRITICAL",
        "cwe_id": "CWE-693",
        "pattern": r'(?:__class__|__mro__|__subclasses__|__globals__)\s*(?:\[|\()',
        "language": "python",
        "category": "CODE_EXECUTION",
        "recommendation": "Use a dedicated sandboxed interpreter (e.g., RestrictedPython) and block dunder attribute access.",
        "confidence": 0.9,
    },

    # =========================================================================
    # RACE CONDITIONS (5 rules)  PY-SEC-121 – PY-SEC-125
    # =========================================================================

    {
        "rule_id": "PY-SEC-121",
        "name": "TOCTOU: os.path.exists then open()",
        "description": "A file's existence is checked with os.path.exists(), then opened separately, creating a TOCTOU race condition.",
        "severity": "MEDIUM",
        "cwe_id": "CWE-367",
        "pattern": r'os\.path\.exists\s*\([^)]+\).*\n.*open\s*\(',
        "language": "python",
        "category": "RACE_CONDITION",
        "recommendation": "Open the file directly and handle the FileNotFoundError exception instead of pre-checking existence.",
        "confidence": 0.7,
    },
    {
        "rule_id": "PY-SEC-122",
        "name": "TOCTOU: os.access then file operation",
        "description": "os.access() is used to check permissions before a file operation, creating a TOCTOU window.",
        "severity": "MEDIUM",
        "cwe_id": "CWE-367",
        "pattern": r'os\.access\s*\([^)]+\)',
        "language": "python",
        "category": "RACE_CONDITION",
        "recommendation": "Rely on exception handling instead of os.access(). os.access() uses real UID/GID and is inherently racy.",
        "confidence": 0.75,
    },
    {
        "rule_id": "PY-SEC-123",
        "name": "Unsynchronized Global State Mutation",
        "description": "A global variable is mutated in a function without a lock, which is unsafe in multi-threaded environments.",
        "severity": "MEDIUM",
        "cwe_id": "CWE-362",
        "pattern": r'^global\s+\w+\s*\n(?:.*\n)*?\s*\w+\s*(?:\+|-|\*|/)?=',
        "language": "python",
        "category": "RACE_CONDITION",
        "recommendation": "Use threading.Lock() to protect shared global state. Consider using threading.local() for per-thread state.",
        "confidence": 0.6,
    },
    {
        "rule_id": "PY-SEC-124",
        "name": "Thread-Unsafe Singleton Pattern",
        "description": "A singleton is implemented without a double-checked locking pattern, making it unsafe under concurrent access.",
        "severity": "MEDIUM",
        "cwe_id": "CWE-362",
        "pattern": r'if\s+(?:cls\._instance|self\._instance)\s+is\s+None\s*:(?:(?!Lock).)*?(?:cls\._instance|self\._instance)\s*=',
        "language": "python",
        "category": "RACE_CONDITION",
        "recommendation": "Use threading.Lock() with double-checked locking or use a module-level singleton (module import is thread-safe).",
        "confidence": 0.65,
    },
    {
        "rule_id": "PY-SEC-125",
        "name": "Async Race Condition: Shared Mutable State Without Lock",
        "description": "An asyncio coroutine modifies shared mutable state without using asyncio.Lock(), risking race conditions.",
        "severity": "MEDIUM",
        "cwe_id": "CWE-362",
        "pattern": r'async def \w+.*:\n(?:.*\n)*?\s*(?:self\.\w+|global \w+)\s*(?:\+|-|\*|/)?=(?!.*await.*Lock)',
        "language": "python",
        "category": "RACE_CONDITION",
        "recommendation": "Use asyncio.Lock() to protect shared mutable state accessed from multiple coroutines.",
        "confidence": 0.6,
    },

    # =========================================================================
    # XML / XXE (10 rules)  PY-SEC-126 – PY-SEC-135
    # =========================================================================

    {
        "rule_id": "PY-SEC-126",
        "name": "XXE via xml.etree.ElementTree",
        "description": "xml.etree.ElementTree.parse() is vulnerable to XXE in Python < 3.8 and processes external entities.",
        "severity": "HIGH",
        "cwe_id": "CWE-611",
        "pattern": r'xml\.etree\.ElementTree\.(?:parse|fromstring|XML)\s*\(',
        "language": "python",
        "category": "XXE",
        "recommendation": "Use defusedxml.ElementTree instead to block external entity expansion.",
        "confidence": 0.8,
    },
    {
        "rule_id": "PY-SEC-127",
        "name": "XXE via lxml with resolve_entities",
        "description": "lxml parser is configured with resolve_entities=True, enabling XXE attacks.",
        "severity": "HIGH",
        "cwe_id": "CWE-611",
        "pattern": r'lxml\.etree\.XMLParser\s*\([^)]*resolve_entities\s*=\s*True',
        "language": "python",
        "category": "XXE",
        "recommendation": "Set resolve_entities=False and no_network=True in lxml's XMLParser.",
        "confidence": 0.95,
    },
    {
        "rule_id": "PY-SEC-128",
        "name": "XXE via xml.sax Parser",
        "description": "xml.sax.parseString() or parse() processes external entities by default.",
        "severity": "HIGH",
        "cwe_id": "CWE-611",
        "pattern": r'xml\.sax\.(?:parseString|parse|make_parser)\s*\(',
        "language": "python",
        "category": "XXE",
        "recommendation": "Use defusedxml.sax.parse() which disables external entity processing.",
        "confidence": 0.8,
    },
    {
        "rule_id": "PY-SEC-129",
        "name": "XXE via xml.dom.minidom",
        "description": "xml.dom.minidom.parseString() expands external entities, enabling XXE.",
        "severity": "HIGH",
        "cwe_id": "CWE-611",
        "pattern": r'xml\.dom\.minidom\.(?:parseString|parse)\s*\(',
        "language": "python",
        "category": "XXE",
        "recommendation": "Use defusedxml.minidom.parseString() which is protected against XXE.",
        "confidence": 0.8,
    },
    {
        "rule_id": "PY-SEC-130",
        "name": "defusedxml Not Used for XML Parsing",
        "description": "Standard library XML parsers are used instead of defusedxml, leaving XXE protections in the developer's hands.",
        "severity": "MEDIUM",
        "cwe_id": "CWE-611",
        "pattern": r'import xml\.(?:etree|sax|dom|parsers)',
        "language": "python",
        "category": "XXE",
        "recommendation": "Replace xml.* imports with equivalent defusedxml imports for safer XML processing.",
        "confidence": 0.7,
    },
    {
        "rule_id": "PY-SEC-131",
        "name": "Billion Laughs / XML Bomb",
        "description": "No entity expansion limit is set, making the parser vulnerable to exponential entity expansion (Billion Laughs).",
        "severity": "HIGH",
        "cwe_id": "CWE-776",
        "pattern": r'xml\.etree\.ElementTree',
        "language": "python",
        "category": "XXE",
        "recommendation": "Use defusedxml which limits entity expansion, or configure lxml with huge_tree=False.",
        "confidence": 0.65,
    },
    {
        "rule_id": "PY-SEC-132",
        "name": "XPath Injection via lxml",
        "description": "lxml XPath expression is constructed with user data, enabling injection.",
        "severity": "HIGH",
        "cwe_id": "CWE-643",
        "pattern": r'\.xpath\s*\(\s*(?:f["\']|["\'][^"\']*\+)',
        "language": "python",
        "category": "XXE",
        "recommendation": "Use XPath variable bindings: tree.xpath('//user[@id=$uid]', uid=user_id)",
        "confidence": 0.85,
    },
    {
        "rule_id": "PY-SEC-133",
        "name": "XSLT Injection",
        "description": "An XSLT stylesheet is loaded from user input and applied, enabling server-side code execution via XSLT.",
        "severity": "CRITICAL",
        "cwe_id": "CWE-91",
        "pattern": r'lxml\.etree\.XSLT\s*\(\s*(?:request\.|user_)',
        "language": "python",
        "category": "XXE",
        "recommendation": "Load XSLT stylesheets from static files only. Never accept stylesheets from user input.",
        "confidence": 0.9,
    },
    {
        "rule_id": "PY-SEC-134",
        "name": "XML External Entity via xmltodict",
        "description": "xmltodict.parse() may process external entities depending on the underlying XML library.",
        "severity": "MEDIUM",
        "cwe_id": "CWE-611",
        "pattern": r'xmltodict\.parse\s*\(',
        "language": "python",
        "category": "XXE",
        "recommendation": "Pass the expat parser options to xmltodict to disable external entity processing.",
        "confidence": 0.7,
    },
    {
        "rule_id": "PY-SEC-135",
        "name": "DTD Processing Enabled",
        "description": "lxml is configured to process DTDs (load_dtd=True or no_network=False), enabling XXE.",
        "severity": "HIGH",
        "cwe_id": "CWE-611",
        "pattern": r'XMLParser\s*\([^)]*(?:load_dtd\s*=\s*True|no_network\s*=\s*False)',
        "language": "python",
        "category": "XXE",
        "recommendation": "Set load_dtd=False and no_network=True in lxml's XMLParser.",
        "confidence": 0.9,
    },

    # =========================================================================
    # MISC (15 rules)  PY-SEC-136 – PY-SEC-150
    # =========================================================================

    {
        "rule_id": "PY-SEC-136",
        "name": "Stack Trace Exposed to Client",
        "description": "A full exception traceback is returned in an HTTP response, leaking internal code structure.",
        "severity": "MEDIUM",
        "cwe_id": "CWE-209",
        "pattern": r'traceback\.(?:format_exc|print_exc|format_tb)\s*\(.*(?:response|return|render)',
        "language": "python",
        "category": "MISC",
        "recommendation": "Log the traceback server-side and return only a generic error message to the client.",
        "confidence": 0.8,
    },
    {
        "rule_id": "PY-SEC-137",
        "name": "Verbose Error Message in Response",
        "description": "Exception details are included directly in an HTTP response body, disclosing sensitive implementation details.",
        "severity": "MEDIUM",
        "cwe_id": "CWE-209",
        "pattern": r'(?:JsonResponse|Response|HttpResponse)\s*\(\s*str\s*\(\s*(?:e|err|error|exception)',
        "language": "python",
        "category": "MISC",
        "recommendation": "Return generic error messages to clients. Log exception details internally.",
        "confidence": 0.8,
    },
    {
        "rule_id": "PY-SEC-138",
        "name": "ReDoS: Catastrophic Backtracking Pattern",
        "description": "A regular expression contains a pattern susceptible to catastrophic backtracking (e.g., (a+)+).",
        "severity": "MEDIUM",
        "cwe_id": "CWE-1333",
        "pattern": r're\.(?:compile|match|search|fullmatch)\s*\(["\'].*(?:\(\w\+\)\+|\(\w\+\)\{|\(\w\|\w\)\+|\(\w+\+\)\+)',
        "language": "python",
        "category": "MISC",
        "recommendation": "Rewrite the regex to be possessive or use atomic groups. Consider using the 're2' module for linear-time matching.",
        "confidence": 0.75,
    },
    {
        "rule_id": "PY-SEC-139",
        "name": "Integer Overflow in Security Context",
        "description": "Integer arithmetic is performed on user-supplied values without bounds checking, which may cause unexpected behavior.",
        "severity": "MEDIUM",
        "cwe_id": "CWE-190",
        "pattern": r'(?:int|len)\s*\(\s*request\.\w+\).*(?:\*|\+|\-\-|\+\+)',
        "language": "python",
        "category": "MISC",
        "recommendation": "Validate integer ranges before arithmetic operations. Use Python's arbitrary-precision integers consciously.",
        "confidence": 0.65,
    },
    {
        "rule_id": "PY-SEC-140",
        "name": "Use of assert for Security Checks",
        "description": "assert statements are used for security-critical checks; they are disabled when Python runs with -O (optimize).",
        "severity": "HIGH",
        "cwe_id": "CWE-617",
        "pattern": r'\bassert\b.*(?:auth|permission|is_admin|is_staff|authenticated)',
        "language": "python",
        "category": "MISC",
        "recommendation": "Replace security-critical asserts with explicit if-raise checks that are never optimized away.",
        "confidence": 0.85,
    },
    {
        "rule_id": "PY-SEC-141",
        "name": "Memory Exposure via Format String",
        "description": "A format string with %p or %x may expose memory addresses in debug output or logs.",
        "severity": "LOW",
        "cwe_id": "CWE-134",
        "pattern": r'["\'].*%(?:p|x|X)["\']',
        "language": "python",
        "category": "MISC",
        "recommendation": "Avoid format specifiers that expose memory addresses. Use structured logging instead.",
        "confidence": 0.6,
    },
    {
        "rule_id": "PY-SEC-142",
        "name": "Global Mutable Default Argument",
        "description": "A mutable object (list, dict) is used as a default argument, which is shared across all calls.",
        "severity": "LOW",
        "cwe_id": "CWE-362",
        "pattern": r'def \w+\s*\([^)]*=\s*(?:\[\]|\{\}|\(\))',
        "language": "python",
        "category": "MISC",
        "recommendation": "Use None as the default and create a new mutable object inside the function body.",
        "confidence": 0.8,
    },
    {
        "rule_id": "PY-SEC-143",
        "name": "Insecure Deserialization via ast.literal_eval with Non-Literals",
        "description": "ast.literal_eval is misused on data that should first be validated; complex nested structures can cause DoS.",
        "severity": "MEDIUM",
        "cwe_id": "CWE-400",
        "pattern": r'ast\.literal_eval\s*\(\s*(?:request\.|user_)',
        "language": "python",
        "category": "MISC",
        "recommendation": "Limit the size of input before calling ast.literal_eval and validate the result type.",
        "confidence": 0.7,
    },
    {
        "rule_id": "PY-SEC-144",
        "name": "Use of pickle in Celery Task Queue",
        "description": "Celery is configured to use pickle serializer, which enables remote code execution via crafted task arguments.",
        "severity": "CRITICAL",
        "cwe_id": "CWE-502",
        "pattern": r'CELERY_TASK_SERIALIZER\s*=\s*["\']pickle["\']',
        "language": "python",
        "category": "MISC",
        "recommendation": "Set CELERY_TASK_SERIALIZER='json' and CELERY_ACCEPT_CONTENT=['json'].",
        "confidence": 0.95,
    },
    {
        "rule_id": "PY-SEC-145",
        "name": "Secrets Logged to Console",
        "description": "Variables with names suggesting secrets (password, key, token) are passed to print() or logging calls.",
        "severity": "HIGH",
        "cwe_id": "CWE-532",
        "pattern": r'(?:print|logger\.\w+)\s*\([^)]*(?:password|secret|api_key|private_key|token)',
        "language": "python",
        "category": "MISC",
        "recommendation": "Never log credentials or secrets. Redact sensitive fields before logging.",
        "confidence": 0.8,
    },
    {
        "rule_id": "PY-SEC-146",
        "name": "Pickle Object Used as Cache Value",
        "description": "Pickled data is stored in and retrieved from a shared cache (Redis/memcache), enabling deserialization attacks.",
        "severity": "HIGH",
        "cwe_id": "CWE-502",
        "pattern": r'(?:cache|redis)\.(?:set|get)\s*\([^)]*pickle',
        "language": "python",
        "category": "MISC",
        "recommendation": "Use JSON serialization for cache values. If pickle must be used, sign the data with an HMAC.",
        "confidence": 0.85,
    },
    {
        "rule_id": "PY-SEC-147",
        "name": "Flask TESTING=True Left in Production Config",
        "description": "Flask TESTING=True disables error handling and may expose internal state.",
        "severity": "HIGH",
        "cwe_id": "CWE-489",
        "pattern": r'(?:app|application)\.config\[(?:\'|")TESTING(?:\'|")\]\s*=\s*True',
        "language": "python",
        "category": "MISC",
        "recommendation": "Set TESTING=False in all non-test environments and use environment-based configuration.",
        "confidence": 0.85,
    },
    {
        "rule_id": "PY-SEC-148",
        "name": "Predictable Temporary Directory",
        "description": "A predictable temporary directory path is constructed, making it vulnerable to symlink attacks.",
        "severity": "MEDIUM",
        "cwe_id": "CWE-377",
        "pattern": r'os\.path\.join\s*\(\s*["\'](?:/tmp|/var/tmp)["\'],\s*(?:["\'][^"\']+["\'])',
        "language": "python",
        "category": "MISC",
        "recommendation": "Use tempfile.mkdtemp() to create a unique temporary directory.",
        "confidence": 0.75,
    },
    {
        "rule_id": "PY-SEC-149",
        "name": "Denial of Service via Unbound Recursion",
        "description": "A recursive function called with user-controlled depth parameter can exhaust the stack.",
        "severity": "MEDIUM",
        "cwe_id": "CWE-674",
        "pattern": r'def \w+\s*\([^)]*depth[^)]*\).*\n(?:.*\n)*?\w+\s*\([^)]*depth\s*(?:\+|-)\s*1',
        "language": "python",
        "category": "MISC",
        "recommendation": "Enforce a maximum recursion depth based on a server-side limit, not user input.",
        "confidence": 0.65,
    },
    {
        "rule_id": "PY-SEC-150",
        "name": "Denial of Service via Uncontrolled Resource Allocation",
        "description": "A resource (list, string, bytes) is allocated based on a user-supplied size without an upper bound check.",
        "severity": "MEDIUM",
        "cwe_id": "CWE-770",
        "pattern": r'(?:bytearray|bytes|list|range)\s*\(\s*int\s*\(\s*(?:request\.|user_)',
        "language": "python",
        "category": "MISC",
        "recommendation": "Enforce a server-side maximum size limit before allocating resources based on user-supplied values.",
        "confidence": 0.8,
    },
]
