"""
TythanAI — CI/CD Integration Generator

Generates ready-to-use CI/CD configuration files for TythanAI scanning:
  • GitHub Actions workflow (.github/workflows/ghost-security.yml)
  • GitLab CI template (.gitlab-ci.yml snippet)
  • Pre-commit hook (.pre-commit-config.yaml snippet)

Usage:
    from integrations.ci_generator import CIGenerator
    gen = CIGenerator()

    # Write GitHub Actions workflow to project
    gen.write_github_actions("/path/to/project")

    # Print GitLab CI snippet
    print(gen.gitlab_ci_snippet())
"""
from __future__ import annotations

from pathlib import Path
from typing import Dict, Optional


class CIGenerator:
    """Generates CI/CD integration files for TythanAI."""

    # ── GitHub Actions ─────────────────────────────────────────────────────────

    def github_actions_workflow(
        self,
        min_severity: str = "MEDIUM",
        scan_on_pr: bool = True,
        upload_sarif: bool = True,
        ton_scan: bool = False,
        iac_scan: bool = True,
        fail_on_critical: bool = True,
    ) -> str:
        """Generate a complete GitHub Actions workflow YAML string."""
        pr_trigger = """
  pull_request:
    branches: [main, master]""" if scan_on_pr else ""

        sarif_step = """
      - name: Upload SARIF to GitHub Code Scanning
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: ghost-results.sarif
          category: ghost-security""" if upload_sarif else ""

        ton_step = """
      - name: Ghost TON Contract Scan
        run: |
          python ghost_cli_main.py ton ./contracts/ --min-severity LOW \\
            2>&1 | tee ghost-ton-results.txt || true""" if ton_scan else ""

        iac_step = """
      - name: Ghost IaC Scan
        run: |
          python ghost_cli_main.py iac . \\
            --output json --save ghost-iac-results.json \\
            --min-severity MEDIUM 2>&1 || true""" if iac_scan else ""

        fail_step = """
      - name: Fail on Critical Findings
        run: |
          CRITS=$(python -c "
          import json, sys
          try:
              findings = json.load(open('ghost-results.json'))
              crits = sum(1 for f in findings if f.get('severity') == 'CRITICAL')
              print(crits)
          except: print(0)
          ")
          if [ "$CRITS" -gt "0" ]; then
            echo "::error::$CRITS critical security findings detected"
            exit 1
          fi""" if fail_on_critical else ""

        return f"""# TythanAI Platform CI/CD Integration
# Auto-generated by TythanAI Platform
#
# This workflow:
#   1. Runs Ghost SAST scan on every push and PR
#   2. Uploads results as SARIF to GitHub Code Scanning (visible in Security tab)
#   3. Fails CI if CRITICAL findings are detected
#
# Setup: Copy to .github/workflows/ghost-security.yml

name: TythanAI Scan

on:
  push:
    branches: [main, master, develop]
  schedule:
    - cron: '0 6 * * 1'  # Weekly full scan on Monday{pr_trigger}

permissions:
  contents: read
  security-events: write   # Required for SARIF upload
  pull-requests: write      # Required for PR comments

jobs:
  ghost-security-scan:
    name: TythanAI Scan
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Full history for incremental scan

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: pip

      - name: Install TythanAI
        run: |
          pip install -e . 2>/dev/null || pip install \\
            pyyaml requests httpx fastapi uvicorn pydantic \\
            2>/dev/null || true

      - name: TythanAI Scan
        id: ghost_scan
        run: |
          python ghost_cli_main.py scan . \\
            --min-severity {min_severity} \\
            --output json \\
            --save ghost-results.json \\
            --no-fail 2>&1 | tee ghost-scan.log

      - name: Export SARIF
        if: always()
        run: |
          python -c "
          import json
          from reports.sarif_exporter import SARIFExporter
          try:
              findings = json.load(open('ghost-results.json'))
              report   = {{'findings': findings}}
              SARIFExporter().export_to_file(report, 'ghost-results.sarif')
              print(f'SARIF exported: {{len(findings)}} findings')
          except Exception as e:
              print(f'SARIF export failed: {{e}}')
              # Create minimal valid SARIF
              import time
              sarif = {{
                  '\\$schema': 'https://json.schemastore.org/sarif-2.1.0.json',
                  'version': '2.1.0',
                  'runs': [{{'tool': {{'driver': {{'name': 'TythanAI', 'version': '1.0'}}}}, 'results': []}}]
              }}
              json.dump(sarif, open('ghost-results.sarif', 'w'))
          "
{sarif_step}
{ton_step}
{iac_step}
      - name: Post PR Comment
        if: github.event_name == 'pull_request' && always()
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            try {{
              const findings = JSON.parse(fs.readFileSync('ghost-results.json', 'utf8'));
              const counts = {{}};
              for (const f of findings) {{
                counts[f.severity] = (counts[f.severity] || 0) + 1;
              }}
              const summary = Object.entries(counts)
                .map(([s, n]) => `${{s}}: ${{n}}`)
                .join(' | ');
              const top = findings
                .filter(f => ['CRITICAL','HIGH'].includes(f.severity))
                .slice(0, 5)
                .map(f => `- **[${{f.severity}}]** \`${{f.file || ''}}:${{f.line || ''}}\` — ${{f.message || f.description || ''}}`)
                .join('\\n');
              const body = findings.length === 0
                ? '✅ **TythanAI**: No findings detected.'
                : `⚠️ **TythanAI** found ${{findings.length}} issues (${{summary}})\\n\\n${{top || ''}}\\n\\n[Full SARIF report in Security tab]`;
              await github.rest.issues.createComment({{
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body
              }});
            }} catch (e) {{
              console.log('Could not post comment:', e.message);
            }}

      - name: Upload Results Artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ghost-security-results
          path: |
            ghost-results.json
            ghost-results.sarif
            ghost-scan.log
          retention-days: 30
{fail_step}
"""

    def write_github_actions(
        self,
        project_root: str,
        **kwargs,
    ) -> str:
        """Write GitHub Actions workflow to .github/workflows/ghost-security.yml."""
        root        = Path(project_root)
        workflows   = root / ".github" / "workflows"
        workflows.mkdir(parents=True, exist_ok=True)
        target = workflows / "ghost-security.yml"
        content = self.github_actions_workflow(**kwargs)
        target.write_text(content)
        return str(target)

    # ── GitLab CI ──────────────────────────────────────────────────────────────

    def gitlab_ci_snippet(self, min_severity: str = "MEDIUM") -> str:
        return f"""# TythanAI Platform — GitLab CI snippet
# Add to your .gitlab-ci.yml

ghost-security-scan:
  stage: test
  image: python:3.11-slim
  before_script:
    - pip install pyyaml requests httpx 2>/dev/null || true
  script:
    - python ghost_cli_main.py scan . --min-severity {min_severity} --output json --save ghost-results.json --no-fail
    - python -c "
      import json
      findings = json.load(open('ghost-results.json'))
      crits = sum(1 for f in findings if f.get('severity') == 'CRITICAL')
      print(f'Findings: {{len(findings)}}  Criticals: {{crits}}')
      exit(1 if crits > 0 else 0)
      "
  artifacts:
    paths:
      - ghost-results.json
    reports:
      sast: ghost-results.json
    expire_in: 1 week
  allow_failure: false
  only:
    - merge_requests
    - main
    - master
"""

    # ── Pre-commit hook ────────────────────────────────────────────────────────

    def pre_commit_config(self) -> str:
        return """# TythanAI pre-commit hook
# Add to .pre-commit-config.yaml

repos:
  - repo: local
    hooks:
      - id: ghost-security-scan
        name: TythanAI Scan
        entry: python ghost_cli_main.py scan
        language: system
        args: [--min-severity, HIGH, --no-fail]
        types: [python, javascript, typescript]
        pass_filenames: false
"""

    # ── Pre-commit script ──────────────────────────────────────────────────────

    def pre_commit_script(self) -> str:
        return """#!/bin/sh
# TythanAI pre-commit hook
# Copy to .git/hooks/pre-commit and chmod +x

echo "🔍 TythanAI: scanning staged files..."

# Get list of staged files
STAGED=$(git diff --cached --name-only --diff-filter=ACM | grep -E '\\.(py|js|ts|jsx|tsx|c|cpp|h|hpp)$')

if [ -z "$STAGED" ]; then
    exit 0
fi

CRITS=0
for FILE in $STAGED; do
    if [ -f "$FILE" ]; then
        RESULT=$(python ghost_cli_main.py scan "$FILE" --min-severity CRITICAL --output json --no-fail 2>/dev/null)
        COUNT=$(echo "$RESULT" | python -c "import json,sys; data=json.load(sys.stdin); print(len(data))" 2>/dev/null || echo 0)
        CRITS=$((CRITS + COUNT))
    fi
done

if [ "$CRITS" -gt 0 ]; then
    echo "❌ TythanAI: $CRITS CRITICAL finding(s) in staged files. Fix before committing."
    echo "   Run: python ghost_cli_main.py scan . to see details"
    exit 1
fi

echo "✅ TythanAI: no critical issues in staged files"
exit 0
"""

    def write_pre_commit_hook(self, project_root: str) -> str:
        """Write pre-commit hook to .git/hooks/pre-commit."""
        hook_dir = Path(project_root) / ".git" / "hooks"
        if not hook_dir.exists():
            return ""
        target = hook_dir / "pre-commit"
        target.write_text(self.pre_commit_script())
        target.chmod(0o755)
        return str(target)

    # ── VS Code settings ───────────────────────────────────────────────────────

    def vscode_tasks(self) -> str:
        return """{
  "version": "2.0.0",
  "tasks": [
    {
      "label": "Ghost: Scan Current File",
      "type": "shell",
      "command": "python ghost_cli_main.py scan ${file} --min-severity LOW",
      "group": "test",
      "presentation": { "panel": "shared", "reveal": "always" }
    },
    {
      "label": "Ghost: Full Project Scan",
      "type": "shell",
      "command": "python ghost_cli_main.py scan ${workspaceFolder} --min-severity MEDIUM --save ghost-results.json",
      "group": "test",
      "presentation": { "panel": "shared", "reveal": "always" }
    },
    {
      "label": "Ghost: TON Contract Scan",
      "type": "shell",
      "command": "python ghost_cli_main.py ton ${workspaceFolder} --report",
      "group": "test",
      "presentation": { "panel": "shared", "reveal": "always" }
    }
  ]
}"""
