"""
TythanAI — IR Playbook Generator
Generates structured Incident Response playbooks for critical security findings.
Saves to reports/ir_playbooks/{scan_id}.md
"""
from __future__ import annotations

import logging
import os
import uuid
from datetime import datetime, timezone
from pathlib import Path
from typing import Dict, List, Optional

from pydantic import BaseModel, Field

# ---------------------------------------------------------------------------
# Resolve Finding import — works whether run in-tree or as standalone
# ---------------------------------------------------------------------------
try:
    from backend.core.confidence import Finding
except ModuleNotFoundError:
    import importlib.util as _ilu
    import pathlib as _pl

    _root = _pl.Path(__file__).resolve().parents[2]
    _spec = _ilu.spec_from_file_location(
        "confidence", _root / "backend" / "core" / "confidence.py"
    )
    _mod = _ilu.module_from_spec(_spec)  # type: ignore[arg-type]
    _spec.loader.exec_module(_mod)  # type: ignore[union-attr]
    Finding = _mod.Finding

logger = logging.getLogger("ghost.ir_playbook")

# ---------------------------------------------------------------------------
# Pydantic models
# ---------------------------------------------------------------------------


class PlaybookStep(BaseModel):
    step_number: int
    phase: str  # "immediate"|"containment"|"eradication"|"recovery"|"verification"|"lessons_learned"
    action: str
    rationale: str
    commands: List[str]  # concrete shell/code commands where applicable
    owner: str  # "security-team"|"dev-team"|"ops-team"|"management"
    time_limit: str  # e.g. "30 minutes", "2 hours", "48 hours"


class IRPlaybook(BaseModel):
    playbook_id: str
    scan_id: str
    vulnerability_type: str
    severity: str
    risk_score: float
    attck_ids: List[str]
    cwe_id: str
    affected_file: str
    created_at: str
    steps: List[PlaybookStep]
    blockchain_steps: List[str]  # empty unless blockchain vuln detected

    def to_markdown(self) -> str:
        lines: List[str] = []
        lines.append(f"# Incident Response Playbook: {self.vulnerability_type.replace('_', ' ').title()}")
        lines.append("")
        lines.append("## Metadata")
        lines.append("")
        lines.append(f"| Field | Value |")
        lines.append(f"|-------|-------|")
        lines.append(f"| Playbook ID | `{self.playbook_id}` |")
        lines.append(f"| Scan ID | `{self.scan_id}` |")
        lines.append(f"| Vulnerability Type | {self.vulnerability_type} |")
        lines.append(f"| Severity | **{self.severity}** |")
        lines.append(f"| Risk Score | {self.risk_score:.1f} / 100 |")
        lines.append(f"| CWE ID | {self.cwe_id} |")
        lines.append(f"| Affected File | `{self.affected_file}` |")
        lines.append(f"| Created At | {self.created_at} |")
        if self.attck_ids:
            lines.append(f"| ATT&CK IDs | {', '.join(self.attck_ids)} |")
        lines.append("")

        if self.blockchain_steps:
            lines.append("## Blockchain-Specific Emergency Actions")
            lines.append("")
            lines.append("> **WARNING**: Smart contract vulnerability detected. Execute these steps IMMEDIATELY before standard IR.")
            lines.append("")
            for i, step in enumerate(self.blockchain_steps, 1):
                lines.append(f"{i}. {step}")
            lines.append("")

        lines.append("## Response Steps")
        lines.append("")

        phases_seen: List[str] = []
        for step in self.steps:
            if step.phase not in phases_seen:
                phases_seen.append(step.phase)
                lines.append(f"### Phase: {step.phase.replace('_', ' ').title()}")
                lines.append("")

            lines.append(f"#### Step {step.step_number}: {step.action}")
            lines.append("")
            lines.append(f"- **Owner**: {step.owner}")
            lines.append(f"- **Time Limit**: {step.time_limit}")
            lines.append(f"- **Rationale**: {step.rationale}")
            if step.commands:
                lines.append("")
                lines.append("```bash")
                for cmd in step.commands:
                    lines.append(cmd)
                lines.append("```")
            lines.append("")

        lines.append("---")
        lines.append(f"*Generated by TythanAI IR Playbook Generator at {self.created_at}*")
        return "\n".join(lines)


# ---------------------------------------------------------------------------
# ATT&CK mapping
# ---------------------------------------------------------------------------

_ATTCK_MAPPING: Dict[str, List[str]] = {
    "sql_injection": ["T1190", "T1059.007", "T1565.001"],
    "remote_code_execution": ["T1190", "T1059", "T1055", "T1210"],
    "hardcoded_credentials": ["T1552.001", "T1078", "T1133"],
    "path_traversal": ["T1083", "T1190", "T1005"],
    "weak_cryptography": ["T1600", "T1557", "T1040"],
    "xss": ["T1059.007", "T1185", "T1539"],
    "supply_chain": ["T1195", "T1195.001", "T1195.002", "T1554"],
    "insecure_deserialization": ["T1059", "T1190", "T1210"],
    "auth_bypass": ["T1078", "T1556", "T1550"],
    "default": ["T1190", "T1059"],
}

# ---------------------------------------------------------------------------
# Playbook templates
# ---------------------------------------------------------------------------

_PLAYBOOK_TEMPLATES: Dict[str, List[dict]] = {
    "sql_injection": [
        {
            "phase": "immediate",
            "action": "Isolate affected database endpoint from public access",
            "rationale": "Prevent continued exploitation while the patch is prepared",
            "commands": [
                "# Block inbound traffic to DB port at firewall",
                "iptables -I INPUT -p tcp --dport 5432 -s 0.0.0.0/0 -j DROP",
                "# Or via cloud security group — example AWS CLI:",
                "aws ec2 revoke-security-group-ingress --group-id sg-XXXXXX --protocol tcp --port 5432 --cidr 0.0.0.0/0",
            ],
            "owner": "ops-team",
            "time_limit": "30 minutes",
        },
        {
            "phase": "immediate",
            "action": "Enable verbose database query logging to capture attack payload",
            "rationale": "Preserve forensic evidence of any SQL injection attempts",
            "commands": [
                "# PostgreSQL: enable full query logging",
                "ALTER SYSTEM SET log_statement = 'all';",
                "SELECT pg_reload_conf();",
                "# MySQL equivalent",
                "SET GLOBAL general_log = 'ON';",
            ],
            "owner": "security-team",
            "time_limit": "30 minutes",
        },
        {
            "phase": "containment",
            "action": "Review DB transaction logs for unauthorized data access and apply WAF rule to block injection patterns",
            "rationale": "Determine scope of potential data exfiltration and add a defence layer while code fix is prepared",
            "commands": [
                "# Export recent DB audit logs",
                "grep -i 'union\\|select.*from\\|drop\\|insert\\|update\\|delete' /var/log/postgresql/postgresql-*.log | tail -5000 > /tmp/sqli_audit.log",
                "# Check for unusual queries from app service account",
                "grep 'app_user' /var/log/postgresql/postgresql-*.log | grep -v 'SELECT\\|INSERT' | tail -1000",
                "# ModSecurity — enable CRS SQL injection rules",
                "# SecRuleEngine On  # add to modsec.conf",
                "# Or via nginx + naxsi: Add DenyRule ID:1000 to /etc/nginx/naxsi.rules",
                "systemctl reload nginx",
            ],
            "owner": "security-team",
            "time_limit": "2 hours",
        },
        {
            "phase": "eradication",
            "action": "Migrate vulnerable query to parameterized/prepared statements",
            "rationale": "Parameterized queries eliminate SQL injection at root cause",
            "commands": [
                "# Python sqlalchemy — UNSAFE:",
                "# engine.execute(f\"SELECT * FROM users WHERE id={user_id}\")",
                "# SAFE replacement:",
                "# engine.execute(text(\"SELECT * FROM users WHERE id=:uid\"), uid=user_id)",
                "# Run static analysis to find remaining unsafe queries",
                "grep -rn 'execute.*f\"\\|execute.*%s\\|execute.*format(' src/ --include='*.py'",
            ],
            "owner": "dev-team",
            "time_limit": "4 hours",
        },
        {
            "phase": "eradication",
            "action": "Rotate all database credentials exposed during the incident",
            "rationale": "Credentials may have been exfiltrated via injected queries",
            "commands": [
                "# Generate new strong password",
                "openssl rand -base64 32 | tr -dc 'a-zA-Z0-9' | head -c 32",
                "# Update in secrets manager",
                "aws secretsmanager update-secret --secret-id prod/db/password --secret-string '{\"password\":\"NEW_PASSWORD\"}'",
                "# Rotate PostgreSQL user password",
                "psql -c \"ALTER USER app_user WITH PASSWORD 'NEW_PASSWORD';\"",
            ],
            "owner": "security-team",
            "time_limit": "2 hours",
        },
        {
            "phase": "recovery",
            "action": "Deploy patched application version and re-enable database access",
            "rationale": "Restore service with hardened code in place",
            "commands": [
                "# Deploy via CI/CD",
                "git tag -a hotfix-sqli-$(date +%Y%m%d) -m 'SQL injection hotfix'",
                "git push origin --tags",
                "# Trigger deployment",
                "kubectl rollout restart deployment/app-backend",
                "kubectl rollout status deployment/app-backend --timeout=5m",
            ],
            "owner": "dev-team",
            "time_limit": "4 hours",
        },
        {
            "phase": "verification",
            "action": "Run automated SQL injection scanner against the patched endpoint",
            "rationale": "Confirm the fix is effective before declaring resolution",
            "commands": [
                "# sqlmap automated scan (safe mode, no actual exploitation)",
                "sqlmap -u 'https://app.example.com/api/resource?id=1' --batch --level=3 --risk=1 --random-agent",
                "# OWASP ZAP passive scan",
                "zap-cli --zap-path /usr/local/zap quick-scan --self-contained --start-options '-config api.disablekey=true' https://app.example.com",
            ],
            "owner": "security-team",
            "time_limit": "2 hours",
        },
        {
            "phase": "lessons_learned",
            "action": "Update SDLC to enforce parameterized queries via SAST and code review checklist",
            "rationale": "Systemic controls prevent regression and similar issues in new code",
            "commands": [
                "# Add semgrep rule to CI pipeline",
                "cat > .semgrep/sqli-check.yaml << 'EOF'",
                "rules:",
                "  - id: unsafe-sql-execute",
                "    pattern: $DB.execute(f\"...\", ...)",
                "    message: Use parameterized queries instead of f-strings in SQL",
                "    severity: ERROR",
                "EOF",
            ],
            "owner": "dev-team",
            "time_limit": "48 hours",
        },
    ],

    "remote_code_execution": [
        {
            "phase": "immediate",
            "action": "Isolate affected host from network immediately",
            "rationale": "Prevent attacker lateral movement and command & control",
            "commands": [
                "# Emergency network isolation",
                "iptables -P INPUT DROP",
                "iptables -P OUTPUT DROP",
                "iptables -P FORWARD DROP",
                "# Allow only SSH from known admin IP",
                "iptables -A INPUT -s ADMIN_IP -p tcp --dport 22 -j ACCEPT",
                "iptables -A OUTPUT -d ADMIN_IP -p tcp --sport 22 -j ACCEPT",
            ],
            "owner": "ops-team",
            "time_limit": "15 minutes",
        },
        {
            "phase": "immediate",
            "action": "Capture memory dump and running process list for forensic analysis",
            "rationale": "Volatile evidence must be captured before remediation destroys it",
            "commands": [
                "# List all running processes with full command lines",
                "ps auxwwf > /tmp/ir_processes_$(date +%Y%m%d_%H%M%S).txt",
                "# List network connections",
                "ss -ntlpu > /tmp/ir_netstat_$(date +%Y%m%d_%H%M%S).txt",
                "# Capture memory with LiME (if available)",
                "# insmod /path/to/lime.ko 'path=/tmp/mem.lime format=lime'",
                "# Or use avml",
                "avml /tmp/memory_$(date +%Y%m%d_%H%M%S).lime 2>/dev/null || true",
            ],
            "owner": "security-team",
            "time_limit": "30 minutes",
        },
        {
            "phase": "containment",
            "action": "Kill suspicious child processes and restart container with process isolation",
            "rationale": "Stop ongoing malicious activity and limit further damage via read-only filesystem",
            "commands": [
                "# Find processes with suspicious parent (e.g. web server spawning shells)",
                "pstree -p $(pgrep -f 'gunicorn\\|uvicorn\\|nginx\\|apache') | grep -v 'python\\|node'",
                "# Kill suspicious processes: kill -9 <PID>",
                "# Check for cron persistence",
                "crontab -l -u www-data 2>/dev/null",
                "# Restart container with read-only root filesystem",
                "docker stop app_container",
                "docker run --read-only --tmpfs /tmp --tmpfs /run -d app_image:latest",
                "# Or Kubernetes",
                "kubectl patch deployment app-backend -p '{\"spec\":{\"template\":{\"spec\":{\"securityContext\":{\"readOnlyRootFilesystem\":true}}}}}'",
            ],
            "owner": "security-team",
            "time_limit": "1 hour",
        },
        {
            "phase": "eradication",
            "action": "Identify and patch the vulnerable code path that allowed RCE",
            "rationale": "Remove root cause to prevent re-exploitation",
            "commands": [
                "# Scan for unsafe eval/exec/subprocess calls",
                "grep -rn 'eval(\\|exec(\\|subprocess.call\\|os.system' src/ --include='*.py'",
                "# Check for unsafe deserialization",
                "grep -rn 'pickle.loads\\|yaml.load(\\|marshal.loads' src/ --include='*.py'",
                "# For template injection",
                "grep -rn 'render_template_string\\|Template(' src/ --include='*.py'",
            ],
            "owner": "dev-team",
            "time_limit": "4 hours",
        },
        {
            "phase": "eradication",
            "action": "Scan filesystem for dropped payloads, webshells, and backdoors",
            "rationale": "Attacker may have planted persistence mechanisms",
            "commands": [
                "# Find recently modified files in web root",
                "find /var/www /opt/app -name '*.py' -newer /tmp/ir_start -type f 2>/dev/null",
                "# Scan for webshells",
                "grep -rn 'eval(base64\\|exec(base64\\|system($_\\|passthru(' /var/www/ 2>/dev/null",
                "# Check for SUID binaries modified recently",
                "find / -perm /4000 -newer /tmp/ir_start -type f 2>/dev/null",
            ],
            "owner": "security-team",
            "time_limit": "3 hours",
        },
        {
            "phase": "recovery",
            "action": "Rebuild affected systems from known-good images",
            "rationale": "Guarantees no persistent malware remains on the system",
            "commands": [
                "# Pull latest clean base image",
                "docker pull app_image:${LAST_KNOWN_GOOD_TAG}",
                "# Re-deploy with security hardening",
                "kubectl apply -f k8s/deployment-hardened.yaml",
                "# Verify integrity",
                "kubectl rollout status deployment/app-backend",
                "# Run smoke tests",
                "python -m pytest tests/smoke/ -v",
            ],
            "owner": "ops-team",
            "time_limit": "4 hours",
        },
        {
            "phase": "verification",
            "action": "Run penetration test against patched endpoint to confirm RCE is closed",
            "rationale": "Independent verification that the vulnerability is resolved",
            "commands": [
                "# Nuclei scan with RCE templates",
                "nuclei -u https://app.example.com -t cves/ -t exposures/ -severity critical,high",
                "# Manual verification with safe PoC",
                "curl -s 'https://app.example.com/endpoint' --data 'input=;id;' | grep -c 'uid='",
            ],
            "owner": "security-team",
            "time_limit": "2 hours",
        },
        {
            "phase": "lessons_learned",
            "action": "Implement input validation framework and sandbox execution for user-controlled data",
            "rationale": "Defence-in-depth prevents future RCE even if input validation is bypassed",
            "commands": [
                "# Add seccomp profile to containers",
                "# In docker-compose.yml:",
                "# security_opt:",
                "#   - seccomp:/path/to/seccomp-profile.json",
                "# Add AppArmor/SELinux mandatory access control",
                "aa-enforce /etc/apparmor.d/app-profile",
            ],
            "owner": "ops-team",
            "time_limit": "72 hours",
        },
    ],

    "hardcoded_credentials": [
        {
            "phase": "immediate",
            "action": "Revoke and rotate all exposed credentials immediately",
            "rationale": "Hardcoded credentials must be considered fully compromised",
            "commands": [
                "# Rotate AWS credentials",
                "aws iam delete-access-key --access-key-id EXPOSED_KEY_ID",
                "aws iam create-access-key --user-name service-account > /tmp/new_creds.json",
                "# Rotate API keys — check service dashboards",
                "# GitHub: Settings > Developer settings > Personal access tokens > Revoke",
                "# Stripe, Twilio, etc.: Login to each provider and rotate",
            ],
            "owner": "security-team",
            "time_limit": "30 minutes",
        },
        {
            "phase": "immediate",
            "action": "Scrub hardcoded credentials from git history",
            "rationale": "Credentials remain accessible in git history even after removal from code",
            "commands": [
                "# Install git-filter-repo",
                "pip install git-filter-repo",
                "# Remove specific file containing secret from all history",
                "git filter-repo --path config/secrets.py --invert-paths",
                "# Or replace secret value throughout history",
                "git filter-repo --replace-text <(echo 'EXPOSED_SECRET==>REDACTED')",
                "# Force push rewritten history (requires coordination with team)",
                "# git push origin --force --all",
                "# Force GitHub to GC the old objects",
                "# Contact GitHub support to purge cached objects if public repo",
            ],
            "owner": "dev-team",
            "time_limit": "2 hours",
        },
        {
            "phase": "containment",
            "action": "Audit access logs for the exposed credentials",
            "rationale": "Determine if credentials were already used by an attacker",
            "commands": [
                "# AWS CloudTrail — check for unusual API calls with exposed key",
                "aws cloudtrail lookup-events --lookup-attributes AttributeKey=AccessKeyId,AttributeValue=EXPOSED_KEY --start-time $(date -d '30 days ago' --iso-8601=seconds)",
                "# Check GitHub audit log for PAT usage",
                "gh api /orgs/YOUR_ORG/audit-log --paginate | jq '.[] | select(.actor_ip != null)'",
            ],
            "owner": "security-team",
            "time_limit": "2 hours",
        },
        {
            "phase": "eradication",
            "action": "Migrate secrets to Vault/secrets manager and enable pre-commit detection",
            "rationale": "Systematic secret management prevents recurrence; automated detection catches leaks before commit",
            "commands": [
                "# Write secret to Vault",
                "vault kv put secret/app/database password='${NEW_DB_PASSWORD}'",
                "# Or AWS Secrets Manager",
                "aws secretsmanager create-secret --name prod/app/db --secret-string '{\"password\":\"NEW_PASSWORD\"}'",
                "# Install detect-secrets pre-commit hook",
                "pip install detect-secrets",
                "detect-secrets scan > .secrets.baseline",
                "pre-commit install",
            ],
            "owner": "dev-team",
            "time_limit": "8 hours",
        },
        {
            "phase": "verification",
            "action": "Scan all repositories for remaining hardcoded secrets",
            "rationale": "Verify no other secrets exist in the codebase",
            "commands": [
                "# truffleHog scan",
                "trufflehog filesystem . --only-verified",
                "# gitleaks scan",
                "gitleaks detect --source . --report-format json --report-path /tmp/gitleaks_report.json",
                "# Check report",
                "cat /tmp/gitleaks_report.json | python -m json.tool | grep 'Match'",
            ],
            "owner": "security-team",
            "time_limit": "2 hours",
        },
        {
            "phase": "lessons_learned",
            "action": "Implement mandatory secrets scanning in CI/CD pipeline",
            "rationale": "Block merges containing secrets automatically",
            "commands": [
                "# Add to GitHub Actions workflow",
                "# - name: Scan for secrets",
                "#   uses: gitleaks/gitleaks-action@v2",
                "#   env:",
                "#     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}",
                "# Enforce secret scanning on GitHub org",
                "gh api -X PATCH /orgs/YOUR_ORG --field secret_scanning_enabled_for_new_repositories=true",
            ],
            "owner": "management",
            "time_limit": "48 hours",
        },
    ],

    "path_traversal": [
        {
            "phase": "immediate",
            "action": "Restrict file access permissions and apply chroot jail to the application",
            "rationale": "Limit what files the application can access even if traversal succeeds",
            "commands": [
                "# Restrict application user permissions",
                "chown -R root:app /opt/app",
                "chmod -R 750 /opt/app",
                "# Apply chroot (systemd service)",
                "# Add to /etc/systemd/system/app.service:",
                "# RootDirectory=/opt/app/sandbox",
                "# ProtectSystem=strict",
                "# PrivateTmp=true",
                "systemctl daemon-reload && systemctl restart app",
            ],
            "owner": "ops-team",
            "time_limit": "1 hour",
        },
        {
            "phase": "containment",
            "action": "Audit access logs for path traversal attempts",
            "rationale": "Identify what files were accessed and the attack timeline",
            "commands": [
                "# Search access logs for traversal patterns",
                "grep -E '\\.\\./|\\.\\.' /var/log/nginx/access.log | tail -1000 > /tmp/traversal_attempts.log",
                "grep -E '%2e%2e|%252e%252e|%c0%af' /var/log/nginx/access.log >> /tmp/traversal_attempts.log",
                "# Count unique IPs performing traversal",
                "awk '{print $1}' /tmp/traversal_attempts.log | sort | uniq -c | sort -rn | head -20",
            ],
            "owner": "security-team",
            "time_limit": "2 hours",
        },
        {
            "phase": "eradication",
            "action": "Fix path traversal by canonicalizing paths and enforcing base directory",
            "rationale": "Input sanitization must resolve the canonical path before file access",
            "commands": [
                "# Safe Python implementation",
                "# import os",
                "# base = os.path.realpath('/safe/base/dir')",
                "# requested = os.path.realpath(os.path.join(base, user_input))",
                "# if not requested.startswith(base + os.sep):",
                "#     raise ValueError('Path traversal detected')",
                "# Scan for vulnerable patterns",
                "grep -rn 'open(.*request\\|open(.*param\\|open(.*user' src/ --include='*.py'",
            ],
            "owner": "dev-team",
            "time_limit": "4 hours",
        },
        {
            "phase": "eradication",
            "action": "Enable symlink protection and disable directory listing",
            "rationale": "Prevents symlink-based traversal attacks as secondary control",
            "commands": [
                "# Nginx — disable symlink following and directory listing",
                "# server { disable_symlinks on; autoindex off; }",
                "# Apache — disable FollowSymLinks",
                "# Options -FollowSymLinks -Indexes",
                "# Mount filesystem with nosymfollow option",
                "# mount -o remount,nosymfollow /",
                "systemctl reload nginx",
            ],
            "owner": "ops-team",
            "time_limit": "2 hours",
        },
        {
            "phase": "verification",
            "action": "Test path traversal remediation with automated scanner",
            "rationale": "Verify the fix prevents all known traversal encoding variants",
            "commands": [
                "# dotdotpwn scan",
                "dotdotpwn -m http -h app.example.com -o unix -s -b",
                "# Nuclei path traversal templates",
                "nuclei -u https://app.example.com -t exposures/files/ -t vulnerabilities/generic/",
                "# Manual tests",
                "curl -s 'https://app.example.com/files?name=../../../etc/passwd'",
                "curl -s 'https://app.example.com/files?name=%2e%2e%2f%2e%2e%2fetc%2fpasswd'",
            ],
            "owner": "security-team",
            "time_limit": "2 hours",
        },
        {
            "phase": "lessons_learned",
            "action": "Add path traversal SAST rules and integration tests to CI pipeline",
            "rationale": "Automated checks prevent future path traversal vulnerabilities",
            "commands": [
                "# Add semgrep rule",
                "cat > .semgrep/path-traversal.yaml << 'EOF'",
                "rules:",
                "  - id: unsafe-file-open",
                "    pattern: open($X)",
                "    message: Ensure $X is validated against a safe base directory",
                "    severity: WARNING",
                "EOF",
                "semgrep --config .semgrep/path-traversal.yaml src/",
            ],
            "owner": "dev-team",
            "time_limit": "48 hours",
        },
    ],

    "weak_cryptography": [
        {
            "phase": "immediate",
            "action": "Identify all data encrypted with weak algorithms and classify sensitivity",
            "rationale": "Assess the risk exposure from potentially broken encryption",
            "commands": [
                "# Find uses of weak algorithms in codebase",
                "grep -rn 'md5\\|sha1\\|DES\\|RC4\\|ECB\\|3DES\\|blowfish\\|rsa.*512\\|rsa.*1024' src/ --include='*.py' -i",
                "# Check TLS configuration",
                "nmap --script ssl-enum-ciphers -p 443 app.example.com",
                "testssl.sh https://app.example.com 2>&1 | grep -E 'WEAK|LOW|MEDIUM|VULNERABLE'",
            ],
            "owner": "security-team",
            "time_limit": "2 hours",
        },
        {
            "phase": "containment",
            "action": "Disable weak TLS ciphers and enforce TLS 1.2+ immediately",
            "rationale": "Prevent active interception while cipher migration is prepared",
            "commands": [
                "# Nginx — enforce TLS 1.2/1.3 and strong ciphers",
                "# ssl_protocols TLSv1.2 TLSv1.3;",
                "# ssl_ciphers ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384;",
                "# ssl_prefer_server_ciphers on;",
                "nginx -t && systemctl reload nginx",
                "# Apache",
                "# SSLProtocol all -SSLv3 -TLSv1 -TLSv1.1",
                "# SSLCipherSuite HIGH:!aNULL:!MD5:!3DES",
            ],
            "owner": "ops-team",
            "time_limit": "1 hour",
        },
        {
            "phase": "eradication",
            "action": "Replace weak cryptographic functions with modern equivalents",
            "rationale": "MD5/SHA1 for security purposes, DES, and ECB mode are cryptographically broken",
            "commands": [
                "# Python replacements:",
                "# MD5 → hashlib.sha256 or hashlib.sha3_256",
                "# DES/RC4 → AES-256-GCM",
                "# ECB → GCM (authenticated encryption)",
                "# For passwords: bcrypt/argon2 → from argon2 import PasswordHasher",
                "pip install argon2-cffi",
                "# Example migration:",
                "# ph = PasswordHasher(time_cost=3, memory_cost=65536, parallelism=4)",
                "# hash = ph.hash(password)",
            ],
            "owner": "dev-team",
            "time_limit": "8 hours",
        },
        {
            "phase": "eradication",
            "action": "Rotate all cryptographic keys generated with weak algorithms",
            "rationale": "Keys generated by weak RNGs or small key sizes must be considered compromised",
            "commands": [
                "# Generate new RSA-4096 key pair",
                "openssl genrsa -out new_private.pem 4096",
                "openssl rsa -in new_private.pem -pubout -out new_public.pem",
                "# Generate new EC key (preferred)",
                "openssl ecparam -name prime256v1 -genkey -noout -out ec_private.pem",
                "# Update certificate",
                "openssl req -new -x509 -key ec_private.pem -out cert.pem -days 365",
            ],
            "owner": "security-team",
            "time_limit": "4 hours",
        },
        {
            "phase": "verification",
            "action": "Run cryptographic analysis to confirm weak algorithms are eliminated",
            "rationale": "Verify migration is complete and no legacy paths remain",
            "commands": [
                "# Re-scan for weak algorithms",
                "grep -rn 'md5\\|sha1\\|DES\\|RC4\\|ECB' src/ --include='*.py' -i",
                "# Test TLS after fix",
                "testssl.sh --color 0 https://app.example.com 2>&1 | grep -E 'WEAK|LOW|VULNERABLE' && echo 'ISSUES FOUND' || echo 'CLEAN'",
                "# SSLLabs API check",
                "curl -s 'https://api.ssllabs.com/api/v3/analyze?host=app.example.com&publish=off&all=done' | python -m json.tool | grep '\"grade\"'",
            ],
            "owner": "security-team",
            "time_limit": "2 hours",
        },
        {
            "phase": "lessons_learned",
            "action": "Add cryptography policy to developer guidelines and SAST checks",
            "rationale": "Prevent re-introduction of weak cryptography in future code",
            "commands": [
                "# Add bandit security check for crypto issues",
                "bandit -r src/ -t B303,B304,B305,B323,B413,B416 -f json -o /tmp/bandit_crypto.json",
                "# Or semgrep rule",
                "semgrep --config p/cryptography src/",
            ],
            "owner": "dev-team",
            "time_limit": "48 hours",
        },
    ],

    "xss": [
        {
            "phase": "immediate",
            "action": "Deploy Content Security Policy header to mitigate active XSS",
            "rationale": "CSP blocks script execution from injected content without code changes",
            "commands": [
                "# Nginx — add CSP header",
                "# add_header Content-Security-Policy \"default-src 'self'; script-src 'self' 'nonce-{RANDOM}'; object-src 'none'; base-uri 'self';\" always;",
                "# add_header X-XSS-Protection \"1; mode=block\" always;",
                "# add_header X-Content-Type-Options nosniff always;",
                "nginx -t && systemctl reload nginx",
            ],
            "owner": "ops-team",
            "time_limit": "30 minutes",
        },
        {
            "phase": "containment",
            "action": "Audit session tokens for signs of session hijacking",
            "rationale": "XSS is commonly used to steal session cookies",
            "commands": [
                "# Check for duplicate session usage from different IPs",
                "grep 'session_id' /var/log/app/access.log | awk '{print $NF, $1}' | sort | uniq -c | sort -rn | head -50",
                "# Invalidate all active sessions as precaution",
                "# redis-cli FLUSHDB  # if using Redis for sessions",
                "# Or via Django:",
                "# python manage.py shell -c 'from django.contrib.sessions.backends.db import SessionStore; [s.delete() for s in SessionStore.objects.all()]'",
            ],
            "owner": "security-team",
            "time_limit": "1 hour",
        },
        {
            "phase": "eradication",
            "action": "Fix XSS by implementing output encoding and DOMPurify for HTML rendering",
            "rationale": "Context-aware encoding prevents XSS at the injection point",
            "commands": [
                "# Python/Jinja2 — ensure auto-escaping is enabled",
                "# env = Environment(autoescape=True)",
                "# Never use |safe filter on user input",
                "# Frontend — replace innerHTML with DOMPurify",
                "# import DOMPurify from 'dompurify';",
                "# element.innerHTML = DOMPurify.sanitize(userInput);",
                "# Install DOMPurify",
                "npm install dompurify @types/dompurify",
            ],
            "owner": "dev-team",
            "time_limit": "4 hours",
        },
        {
            "phase": "eradication",
            "action": "Set HttpOnly and Secure flags on all session cookies",
            "rationale": "Prevents JavaScript from accessing session cookies even if XSS succeeds",
            "commands": [
                "# Flask/Django — set secure cookie flags",
                "# SESSION_COOKIE_HTTPONLY = True",
                "# SESSION_COOKIE_SECURE = True",
                "# SESSION_COOKIE_SAMESITE = 'Lax'",
                "# Nginx — add Set-Cookie flags",
                "# proxy_cookie_flags ~ HttpOnly;Secure;SameSite=Lax;",
                "nginx -t && systemctl reload nginx",
            ],
            "owner": "dev-team",
            "time_limit": "2 hours",
        },
        {
            "phase": "verification",
            "action": "Run XSS scanner to confirm all injection vectors are closed",
            "rationale": "Automated scanning ensures comprehensive coverage",
            "commands": [
                "# dalfox XSS scanner",
                "dalfox url 'https://app.example.com/search?q=FUZZ' -o /tmp/dalfox_results.txt",
                "# OWASP ZAP active scan",
                "zap-cli active-scan --scanners xss https://app.example.com",
                "# Check CSP grade",
                "curl -sI https://app.example.com | grep -i 'content-security-policy'",
            ],
            "owner": "security-team",
            "time_limit": "2 hours",
        },
        {
            "phase": "lessons_learned",
            "action": "Implement Trusted Types and strict CSP enforcement across the application",
            "rationale": "Trusted Types prevents DOM XSS at browser level for modern browsers",
            "commands": [
                "# Add Trusted Types CSP directive",
                "# require-trusted-types-for 'script'; trusted-types default dompurify;",
                "# Add XSS-focused SAST to CI",
                "semgrep --config p/xss src/",
                "npm run test:security",
            ],
            "owner": "dev-team",
            "time_limit": "72 hours",
        },
    ],

    "supply_chain": [
        {
            "phase": "immediate",
            "action": "Identify and isolate affected package versions across all environments",
            "rationale": "Limit the blast radius of the supply chain compromise",
            "commands": [
                "# List all installed packages with versions",
                "pip freeze > /tmp/pip_freeze_$(date +%Y%m%d).txt",
                "npm list --all --json > /tmp/npm_tree_$(date +%Y%m%d).json 2>/dev/null",
                "# Check if compromised package is installed",
                "pip show PACKAGE_NAME | grep -E 'Name|Version|Location'",
                "# Find all requirements files in repo",
                "find . -name 'requirements*.txt' -o -name 'package*.json' -o -name 'Gemfile*' | xargs grep 'PACKAGE_NAME'",
            ],
            "owner": "security-team",
            "time_limit": "1 hour",
        },
        {
            "phase": "immediate",
            "action": "Generate Software Bill of Materials (SBOM) for all affected projects",
            "rationale": "SBOM enables rapid identification of all transitive dependency exposure",
            "commands": [
                "# Generate SBOM with CycloneDX",
                "cyclonedx-py --format json --output /tmp/sbom_$(date +%Y%m%d).json .",
                "# Or with syft",
                "syft . -o cyclonedx-json > /tmp/sbom_syft.json",
                "# Check against known vulnerable packages",
                "grype /tmp/sbom_syft.json --output table",
            ],
            "owner": "security-team",
            "time_limit": "2 hours",
        },
        {
            "phase": "containment",
            "action": "Pin all dependency versions and disable automatic updates",
            "rationale": "Prevents additional malicious versions from being pulled automatically",
            "commands": [
                "# Pin Python dependencies",
                "pip-compile --generate-hashes requirements.in -o requirements.txt",
                "# Pin npm with package-lock.json",
                "npm ci  # use lock file exactly",
                "# Disable Dependabot auto-merge if configured",
                "gh api -X PATCH /repos/ORG/REPO/automated-security-fixes --field enabled=false",
            ],
            "owner": "dev-team",
            "time_limit": "2 hours",
        },
        {
            "phase": "eradication",
            "action": "Remove or replace compromised dependency with verified safe version",
            "rationale": "Eliminate the malicious code from all environments",
            "commands": [
                "# Uninstall compromised package",
                "pip uninstall -y COMPROMISED_PACKAGE",
                "# Install verified safe version with hash verification",
                "pip install --require-hashes SAFE_PACKAGE==VERSION",
                "# npm",
                "npm uninstall COMPROMISED_PACKAGE",
                "npm install SAFE_PACKAGE@VERSION --save-exact",
                "npm audit fix",
            ],
            "owner": "dev-team",
            "time_limit": "4 hours",
        },
        {
            "phase": "eradication",
            "action": "Audit CI/CD pipeline for supply chain compromise vectors",
            "rationale": "CI/CD pipelines are high-value targets for supply chain attacks",
            "commands": [
                "# Review GitHub Actions workflow files",
                "grep -rn 'uses:' .github/workflows/ | grep -v '@v[0-9]\\|@[a-f0-9]\\{40\\}'",
                "# Pin all actions to specific commit SHAs",
                "# uses: actions/checkout@v3  ->  uses: actions/checkout@abc123def456...",
                "# Scan for script injection in workflows",
                "semgrep --config p/github-actions .github/",
            ],
            "owner": "dev-team",
            "time_limit": "4 hours",
        },
        {
            "phase": "recovery",
            "action": "Rebuild all deployment artifacts from source with verified dependencies",
            "rationale": "Ensures no compromised code remains in deployed artifacts",
            "commands": [
                "# Clear all caches",
                "pip cache purge",
                "npm cache clean --force",
                "docker system prune -af",
                "# Rebuild from scratch",
                "docker build --no-cache -t app:latest .",
                "docker push app:latest",
                "kubectl rollout restart deployment/app-backend",
            ],
            "owner": "ops-team",
            "time_limit": "4 hours",
        },
        {
            "phase": "verification",
            "action": "Verify artifact integrity with cryptographic signatures",
            "rationale": "Confirms rebuilt artifacts are clean",
            "commands": [
                "# Sigstore/cosign for container image signing",
                "cosign sign --key cosign.key app:latest",
                "cosign verify --key cosign.pub app:latest",
                "# SLSA provenance verification",
                "slsa-verifier verify-image app:latest --provenance-path provenance.json",
            ],
            "owner": "security-team",
            "time_limit": "2 hours",
        },
        {
            "phase": "lessons_learned",
            "action": "Implement SLSA Level 2+ supply chain security controls",
            "rationale": "Systematic supply chain security controls prevent future compromises",
            "commands": [
                "# Enable private package registry with audit",
                "# pip.conf: index-url = https://private.pypi.company.com",
                "# npm: registry = https://private.npm.company.com",
                "# Add OSV-Scanner to CI",
                "# - name: OSV-Scanner",
                "#   uses: google/osv-scanner-action@v1",
                "# Subscribe to security advisories for all dependencies",
                "gh api -X PUT /repos/ORG/REPO/vulnerability-alerts",
            ],
            "owner": "management",
            "time_limit": "72 hours",
        },
    ],

    "insecure_deserialization": [
        {
            "phase": "immediate",
            "action": "Disable or firewall the deserialization endpoint",
            "rationale": "Insecure deserialization can lead to immediate RCE; stop exposure first",
            "commands": [
                "# If endpoint is identified, add WAF rule to block serialized object content types",
                "# Nginx — block Java serialized object magic bytes",
                "# if ($http_content_type ~ 'application/x-java-serialized-object') { return 403; }",
                "# Block pickle/marshal Content-Type",
                "# if ($http_content_type ~ 'application/python-pickle') { return 403; }",
                "nginx -t && systemctl reload nginx",
            ],
            "owner": "ops-team",
            "time_limit": "30 minutes",
        },
        {
            "phase": "containment",
            "action": "Review access logs for deserialization exploitation attempts",
            "rationale": "Determine if the vulnerability has already been exploited",
            "commands": [
                "# Search for serialization-related requests",
                "grep -E 'rO0AB|aced0005|pickle|marshal' /var/log/nginx/access.log",
                "# Check for gadget chain indicators in request bodies",
                "grep -E 'CommonsCollections|ysoserial|java.lang.Runtime' /var/log/app/*.log",
            ],
            "owner": "security-team",
            "time_limit": "2 hours",
        },
        {
            "phase": "eradication",
            "action": "Replace insecure deserialization with schema-validated JSON",
            "rationale": "JSON with schema validation eliminates gadget chain attacks",
            "commands": [
                "# Python — replace pickle with JSON + schema validation",
                "# UNSAFE: obj = pickle.loads(user_data)",
                "# SAFE: import json; from pydantic import BaseModel",
                "# obj = MyModel.model_validate_json(user_data)",
                "# For Python: never use pickle on untrusted data",
                "grep -rn 'pickle.loads\\|pickle.load\\|marshal.loads\\|yaml.load(' src/ --include='*.py'",
            ],
            "owner": "dev-team",
            "time_limit": "4 hours",
        },
        {
            "phase": "eradication",
            "action": "Implement allowlist-based deserialization for any required binary formats",
            "rationale": "Allowlisting classes prevents arbitrary gadget chain execution",
            "commands": [
                "# Java — use SerialKiller or JEP 290 filters",
                "# ObjectInputFilter.Config.setSerialFilter(info -> {...});",
                "# Python — use restricted unpickler",
                "# class SafeUnpickler(pickle.Unpickler):",
                "#     def find_class(self, module, name):",
                "#         if (module, name) not in ALLOWED_CLASSES:",
                "#             raise pickle.UnpicklingError('Blocked')",
                "#         return super().find_class(module, name)",
            ],
            "owner": "dev-team",
            "time_limit": "6 hours",
        },
        {
            "phase": "verification",
            "action": "Test deserialization endpoints with ysoserial/pickle gadget chains",
            "rationale": "Confirm gadget chains are blocked",
            "commands": [
                "# Python pickle gadget test (safe PoC)",
                "python3 -c \"import pickle,os; payload = pickle.dumps({'cmd':'id'}); print(len(payload), 'bytes')\"",
                "# Send to endpoint and verify 403/rejection",
                "curl -s -X POST https://app.example.com/api/deserialize -H 'Content-Type: application/octet-stream' --data-binary @/tmp/test_pickle | grep -v 'uid='",
            ],
            "owner": "security-team",
            "time_limit": "2 hours",
        },
        {
            "phase": "lessons_learned",
            "action": "Add deserialization SAST rules and prohibit pickle/marshal in security policy",
            "rationale": "Policy and tooling prevent future introduction of insecure deserialization",
            "commands": [
                "bandit -r src/ -t B301,B302,B303 -f json -o /tmp/bandit_deser.json",
                "cat /tmp/bandit_deser.json | python -m json.tool | grep -A3 '\"issue_text\"'",
                "# Add to code review checklist:",
                "# - No use of pickle.loads() on untrusted data",
                "# - No yaml.load() without Loader=yaml.SafeLoader",
            ],
            "owner": "dev-team",
            "time_limit": "48 hours",
        },
    ],

    "auth_bypass": [
        {
            "phase": "immediate",
            "action": "Invalidate all active sessions and force re-authentication",
            "rationale": "Attacker may have active sessions obtained via bypass; revoke all",
            "commands": [
                "# Invalidate all Redis sessions",
                "redis-cli --scan --pattern 'session:*' | xargs redis-cli del",
                "# Django — rotate secret key to invalidate all session cookies",
                "python manage.py shell -c \"from django.contrib.sessions.models import Session; Session.objects.all().delete()\"",
                "# Rotate JWT secret",
                "openssl rand -hex 64 > /tmp/new_jwt_secret.txt",
                "# Update JWT_SECRET_KEY in secrets manager",
            ],
            "owner": "security-team",
            "time_limit": "30 minutes",
        },
        {
            "phase": "containment",
            "action": "Audit authentication logs for bypass attempts and unauthorized access",
            "rationale": "Identify affected accounts and scope of unauthorized access",
            "commands": [
                "# Search for auth bypass indicators",
                "grep -E 'auth_bypass|bypass|SQLI|admin.*true|role.*admin' /var/log/app/auth.log | tail -5000",
                "# Find accounts with logins from unusual IPs",
                "grep 'login_success' /var/log/app/auth.log | awk '{print $5, $3}' | sort | uniq -c | sort -rn | head -50",
                "# Export user activity for affected time window",
                "grep -E 'admin|superuser|role=high' /var/log/app/audit.log | tail -10000 > /tmp/auth_audit.log",
            ],
            "owner": "security-team",
            "time_limit": "2 hours",
        },
        {
            "phase": "eradication",
            "action": "Fix authentication bypass vulnerability in code",
            "rationale": "Remove the root cause to prevent continued exploitation",
            "commands": [
                "# Common auth bypass patterns to look for and fix:",
                "grep -rn 'if.*bypass\\|auth.*skip\\|no_auth\\|disable.*auth\\|\"admin\"\\|is_admin.*True' src/ --include='*.py'",
                "# Verify JWT validation",
                "grep -rn 'algorithms.*none\\|verify.*False\\|decode.*options' src/ --include='*.py'",
                "# Check for hardcoded credentials",
                "grep -rn 'password.*=.*[\"\\x27]\\|token.*=.*[\"\\x27]' src/ --include='*.py'",
            ],
            "owner": "dev-team",
            "time_limit": "4 hours",
        },
        {
            "phase": "eradication",
            "action": "Enforce MFA for all privileged accounts",
            "rationale": "MFA provides defence-in-depth even if authentication logic is bypassed",
            "commands": [
                "# Enable MFA enforcement via identity provider",
                "# AWS SSO — enforce MFA",
                "aws iam update-account-password-policy --require-symbols --require-uppercase-characters",
                "# Enable MFA in application",
                "# pip install pyotp",
                "# import pyotp; totp = pyotp.TOTP(pyotp.random_base32())",
                "# Enforce MFA for admin role in application settings",
            ],
            "owner": "security-team",
            "time_limit": "4 hours",
        },
        {
            "phase": "verification",
            "action": "Pen test authentication flow to confirm bypass is closed",
            "rationale": "Independent verification that authentication is working correctly",
            "commands": [
                "# Test with invalid tokens",
                "curl -s https://app.example.com/api/admin -H 'Authorization: Bearer invalid_token' | grep -v '200 OK'",
                "# Test JWT algorithm confusion (alg:none)",
                "curl -s https://app.example.com/api/admin -H 'Authorization: Bearer eyJhbGciOiJub25lIn0.eyJ1c2VyIjoiYWRtaW4ifQ.' | grep -v 'admin'",
                "# Nuclei auth bypass templates",
                "nuclei -u https://app.example.com -t vulnerabilities/auth/ -t misconfiguration/",
            ],
            "owner": "security-team",
            "time_limit": "2 hours",
        },
        {
            "phase": "lessons_learned",
            "action": "Implement centralized authentication middleware with mandatory enforcement",
            "rationale": "Centralizing auth prevents per-endpoint bypass opportunities",
            "commands": [
                "# Add auth middleware to all routes",
                "# FastAPI: app.add_middleware(AuthMiddleware)",
                "# Test that all endpoints require auth",
                "pytest tests/security/test_auth_required.py -v",
                "# Add SAST rule for missing auth decorators",
                "semgrep --config p/fastapi src/",
            ],
            "owner": "dev-team",
            "time_limit": "48 hours",
        },
    ],

    "default": [
        {
            "phase": "immediate",
            "action": "Triage the finding and assess immediate risk to production systems",
            "rationale": "Determine if emergency containment is required before detailed analysis",
            "commands": [
                "# Review the affected file and line",
                "cat -n AFFECTED_FILE | tail -n +$((LINE-5)) | head -20",
                "# Check if the vulnerability is reachable from internet",
                "# nmap -p 80,443,8080 app.example.com",
            ],
            "owner": "security-team",
            "time_limit": "1 hour",
        },
        {
            "phase": "containment",
            "action": "Apply compensating control to limit exploit surface while fix is prepared",
            "rationale": "Reduce risk exposure during the remediation window",
            "commands": [
                "# Restrict access to affected functionality if possible",
                "# Enable additional logging/monitoring for the affected code path",
                "# Alert on anomalous usage patterns",
            ],
            "owner": "ops-team",
            "time_limit": "2 hours",
        },
        {
            "phase": "eradication",
            "action": "Develop and test fix for the identified vulnerability",
            "rationale": "Address root cause rather than just symptoms",
            "commands": [
                "# Review finding details and recommendation",
                "# Implement fix following secure coding best practices",
                "# Write unit test to cover the vulnerable code path",
                "python -m pytest tests/ -v -k 'security'",
            ],
            "owner": "dev-team",
            "time_limit": "8 hours",
        },
        {
            "phase": "recovery",
            "action": "Deploy fix to production after testing and code review",
            "rationale": "Restore normal operation with the vulnerability patched",
            "commands": [
                "# Deploy via standard CI/CD pipeline",
                "git push origin main",
                "# Monitor deployment",
                "kubectl rollout status deployment/app-backend --timeout=10m",
            ],
            "owner": "dev-team",
            "time_limit": "4 hours",
        },
        {
            "phase": "lessons_learned",
            "action": "Update security controls and test cases to prevent regression",
            "rationale": "Systemic improvements prevent similar vulnerabilities in future",
            "commands": [
                "# Add regression test",
                "# Update SAST rules if applicable",
                "# Document in security runbook",
            ],
            "owner": "security-team",
            "time_limit": "48 hours",
        },
    ],
}

_BLOCKCHAIN_STEPS: List[str] = [
    "Pause smart contract via emergency pause function",
    "Notify token holders via official channels within 1 hour",
    "Deploy emergency multisig for fund recovery",
    "Audit all transactions in affected block range",
    "Prepare on-chain governance vote for patch deployment",
]

_BLOCKCHAIN_KEYWORDS = frozenset(["blockchain", "token", "reentrancy", "overflow", "contract"])

# ---------------------------------------------------------------------------
# Vuln type detection
# ---------------------------------------------------------------------------

_VULN_TYPE_KEYWORDS: Dict[str, List[str]] = {
    "sql_injection": ["sql", "sqli", "injection", "query", "CWE-89"],
    "remote_code_execution": ["rce", "remote_code", "code_exec", "command_injection", "CWE-78", "CWE-94"],
    "hardcoded_credentials": ["hardcoded", "credential", "secret", "password", "api_key", "CWE-798", "CWE-259"],
    "path_traversal": ["path_traversal", "directory_traversal", "lfi", "CWE-22"],
    # Note: "insecure_deserialization" is checked BEFORE "weak_cryptography" to avoid
    # "deserializ" matching the "des" cipher keyword.
    "insecure_deserialization": ["deserializ", "pickle", "marshal", "CWE-502"],
    "weak_cryptography": ["crypto", "cipher", "md5", "sha1", "weak_hash", " des ", "CWE-327", "CWE-328", "CWE-326"],
    "xss": ["xss", "cross_site", "script_injection", "html_inject", "CWE-79"],
    "supply_chain": ["supply_chain", "dependency", "package", "sbom", "CWE-1104"],
    "auth_bypass": ["auth_bypass", "authentication", "authorization", "jwt", "session", "CWE-287", "CWE-306"],
}


def _detect_vuln_type(rule_id: str, cwe_id: str) -> str:
    combined = (rule_id + " " + cwe_id).lower()
    for vuln_type, keywords in _VULN_TYPE_KEYWORDS.items():
        if any(kw.lower() in combined for kw in keywords):
            return vuln_type
    return "default"


def _is_blockchain_vuln(rule_id: str) -> bool:
    return any(kw in rule_id.lower() for kw in _BLOCKCHAIN_KEYWORDS)


# ---------------------------------------------------------------------------
# Generator class
# ---------------------------------------------------------------------------


class IRPlaybookGenerator:
    def __init__(self, output_dir: Optional[str] = None) -> None:
        if output_dir:
            self._reports_dir = Path(output_dir)
        else:
            self._reports_dir = Path("reports/ir_playbooks")
        self._reports_dir.mkdir(parents=True, exist_ok=True)

    def generate(
        self,
        finding: Finding,
        risk_score: float = 75.0,
        scan_id: Optional[str] = None,
    ) -> Optional["IRPlaybook"]:
        if finding.severity not in ("CRITICAL", "HIGH") and risk_score <= 60:
            return None

        vuln_type = _detect_vuln_type(finding.rule_id, finding.cwe_id)
        template_steps = _PLAYBOOK_TEMPLATES.get(vuln_type, _PLAYBOOK_TEMPLATES["default"])

        steps: List[PlaybookStep] = []
        for idx, tpl in enumerate(template_steps, 1):
            # Fill in finding-specific details in action/rationale where applicable
            action = tpl["action"]
            rationale = tpl["rationale"]
            commands = list(tpl["commands"])

            # Inject file context into first immediate step
            if idx == 1 and tpl["phase"] == "immediate":
                commands.append(f"# Affected file: {finding.file} (line {finding.line})")

            steps.append(
                PlaybookStep(
                    step_number=idx,
                    phase=tpl["phase"],
                    action=action,
                    rationale=rationale,
                    commands=commands,
                    owner=tpl["owner"],
                    time_limit=tpl["time_limit"],
                )
            )

        blockchain_steps: List[str] = (
            _BLOCKCHAIN_STEPS if _is_blockchain_vuln(finding.rule_id) else []
        )

        attck_ids = _ATTCK_MAPPING.get(vuln_type, _ATTCK_MAPPING["default"])
        effective_scan_id = scan_id or str(uuid.uuid4())

        return IRPlaybook(
            playbook_id=str(uuid.uuid4()),
            scan_id=effective_scan_id,
            vulnerability_type=vuln_type,
            severity=finding.severity,
            risk_score=risk_score,
            attck_ids=attck_ids,
            cwe_id=finding.cwe_id or "CWE-0",
            affected_file=finding.file,
            created_at=datetime.now(timezone.utc).isoformat(),
            steps=steps,
            blockchain_steps=blockchain_steps,
        )

    def save(self, playbook: IRPlaybook) -> Path:
        safe_scan_id = playbook.scan_id.replace("/", "_").replace("\\", "_")
        path = self._reports_dir / f"{safe_scan_id}.md"
        path.write_text(playbook.to_markdown(), encoding="utf-8")
        logger.info("IR playbook saved to %s", path)
        return path

    def generate_and_save(
        self,
        finding: Finding,
        risk_score: float = 75.0,
        scan_id: Optional[str] = None,
    ) -> Optional[Path]:
        try:
            playbook = self.generate(finding, risk_score=risk_score, scan_id=scan_id)
            return self.save(playbook)
        except ValueError as exc:
            logger.debug("Playbook not generated: %s", exc)
            return None
        except Exception as exc:
            logger.error("Failed to generate/save IR playbook: %s", exc, exc_info=True)
            return None


# ---------------------------------------------------------------------------
# Module-level convenience function
# ---------------------------------------------------------------------------


def generate_ir_playbook(finding: Finding, risk_score: float = 75.0) -> IRPlaybook:
    """Generate an IR playbook for a critical finding.

    Raises ValueError if the finding does not meet the severity/risk threshold.
    """
    return IRPlaybookGenerator().generate(finding, risk_score=risk_score)
